// features/physician-letters.js
// ═════════════════════════════════════════════════════════════════════════════
// PHYSICIAN LETTERS FEATURE — Self-contained module
// ═════════════════════════════════════════════════════════════════════════════
//
// Workflow (channel-threaded):
//   Post-eval form (Converted + toggle ON)
//     → Claude generates draft
//     → Top-level Slack post in #physician-letters channel (@-mentions PT)
//     → PT approves → ✅ reaction on top-level + threaded reply for admin routing
//     → Admin enters MD info + generates PDF → ✅ on admin reply + threaded "PDF ready" reply
//     → Admin marks faxed → ✅ on PDF ready reply + audit log updated
//   Post-eval form (Converted + toggle OFF — self-referred, declined, etc.)
//     → No Claude call. No PDF. No Drive upload.
//     → Single non-actionable Slack post: "No physician letter needed — J.M."
//     → Audit row logged with status 'letter_skipped' for completeness
//   Friday 5pm PT: weekly summary email to Jordan
//
// Public exports:
//   module.exports                                  — Express router (mount at /eval-letter)
//   module.exports.init                             — call once on startup (arms weekly cron)
//   module.exports.generateAndQueuePhysicianLetter  — called by post-eval handler when toggle ON
//   module.exports.notifyPhysicianLetterSkipped     — called by post-eval handler when toggle OFF
//
// All env vars are read at the top of this file. All clinical content is
// generated by Claude Sonnet 4.6 from the eval transcript.
// ═════════════════════════════════════════════════════════════════════════════

const express = require('express');
const axios = require('axios');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { google } = require('googleapis');
const { Readable } = require('stream');

const router = express.Router();

// ─── CONFIG ──────────────────────────────────────────────────────────────────
// All env vars and constants live here. This is the only place this file
// reads from process.env.

const PHYSICIAN_LETTERS_CHANNEL = process.env.PHYSICIAN_LETTERS_CHANNEL || 'C0B076M7B0E';
const PHYSICIAN_LETTERS_DRIVE_FOLDER = process.env.PHYSICIAN_LETTERS_DRIVE_FOLDER || '1VgLlcCU60c1pvyeQ7-928JgHxnEgSVJr';
const PHYSICIAN_LETTERS_SHEET_ID = process.env.PHYSICIAN_LETTERS_SHEET_ID || '1iM-3NbXz0noloqIY-81EVde9fA_HGM3SGIvmlrxk4lk';
const PHYSICIAN_LETTERS_SHEET_TAB = process.env.PHYSICIAN_LETTERS_SHEET_TAB || 'Sheet1';

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;

const BASE_URL = process.env.RAILWAY_PUBLIC_DOMAIN
  ? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}`
  : 'https://movement-clinic-webhook-production.up.railway.app';

const PT_SLACK_IDS = {
  'John Gan':         'U07TJC6GZFG',
  'TJ Aquino':        'U0A9DL4RTKN',
  'Chris Bostwick':   'U091NMDKTFV',
  'Jordan McCormack': process.env.PT_SLACK_JORDAN || ''
};

const PT_LICENSES = {
  'Jordan McCormack': process.env.PT_LICENSE_JORDAN || 'PT-PENDING',
  'Chris Bostwick':   process.env.PT_LICENSE_CHRIS  || 'PT-PENDING',
  'TJ Aquino':        process.env.PT_LICENSE_TJ     || 'PT-PENDING',
  'John Gan':         process.env.PT_LICENSE_JOHN   || 'PT-PENDING'
};

const PT_CREDENTIALS = {
  'Jordan McCormack': process.env.PT_CREDS_JORDAN || 'PT, DPT',
  'Chris Bostwick':   process.env.PT_CREDS_CHRIS  || 'PT, DPT',
  'TJ Aquino':        process.env.PT_CREDS_TJ     || 'PT, DPT',
  'John Gan':         process.env.PT_CREDS_JOHN   || 'PT, DPT'
};

const CLINIC = {
  name:    process.env.CLINIC_NAME    || 'Movement Clinic Physical Therapy, Inc.',
  addr1:   process.env.CLINIC_ADDR_1  || '[Clinic Street Address]',
  addr2:   process.env.CLINIC_ADDR_2  || 'Pasadena, CA [ZIP]',
  phone:   process.env.CLINIC_PHONE   || '(626) 669-3778',
  fax:     process.env.CLINIC_FAX     || '[Clinic Fax Number]',
  npi:     process.env.CLINIC_NPI     || '[Clinic Group NPI]',
  website: process.env.CLINIC_WEBSITE || 'movementclinicpt.com'
};

// Persistent storage path — Railway volume in prod, /tmp in dev
const LETTER_DRAFTS_DIR = fs.existsSync('/data')
  ? path.join('/data', 'eval-letters')
  : path.join('/tmp', 'eval-letters');
if (!fs.existsSync(LETTER_DRAFTS_DIR)) {
  fs.mkdirSync(LETTER_DRAFTS_DIR, { recursive: true });
}

// ─── STORAGE HELPERS ─────────────────────────────────────────────────────────

function generateLetterToken() {
  return crypto.randomBytes(16).toString('hex');
}

function saveLetterDraft(token, data) {
  const filePath = path.join(LETTER_DRAFTS_DIR, `${token}.json`);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function loadLetterDraft(token) {
  const filePath = path.join(LETTER_DRAFTS_DIR, `${token}.json`);
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function listLetterDrafts() {
  if (!fs.existsSync(LETTER_DRAFTS_DIR)) return [];
  return fs.readdirSync(LETTER_DRAFTS_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return loadLetterDraft(f.replace('.json', '')); }
      catch { return null; }
    })
    .filter(Boolean);
}

function patientInitials(draft) {
  const f = (draft.patient_first_name || '?')[0];
  const l = (draft.patient_last_name || '?')[0];
  return `${f}.${l}.`;
}

// ─── CLAUDE LETTER GENERATION ────────────────────────────────────────────────

const LETTER_GENERATION_PROMPT = `You are a clinical writer for Movement Clinic Physical Therapy, an outpatient clinic in Pasadena, CA. You generate professional Initial Evaluation Summary letters that physical therapists send to a patient's referring or primary care physician.

Your output is a structured JSON object that will be reviewed by the evaluating PT before being sent. Be clinically precise, factually grounded in the transcript, and avoid embellishment.

CRITICAL RULES:
1. Only include findings that are explicitly stated or unambiguously implied in the transcript.
2. If something is not in the transcript, do NOT make it up. Use "Not assessed during evaluation" or omit the field.
3. Use professional clinical terminology that an MD will recognize (e.g., "external rotator weakness 4-/5", "limited active shoulder flexion ~150°").
4. Distinguish between subjective complaints (what the patient said) and objective findings (what the PT measured).
5. Mark the "confidence" field honestly — "high" if the transcript was thorough, "medium" if some sections are sparse, "low" if you had to infer significantly.

Return ONLY valid JSON in this exact schema:

{
  "patient_summary": {
    "chief_complaint": "Brief one-sentence summary of primary concern",
    "onset": "Duration and mechanism (e.g., '3.5 months ago, insidious onset, no known trauma')",
    "aggravating_factors": "What makes it worse",
    "relieving_factors": "What makes it better",
    "prior_treatment": "Any prior care for this issue (or 'None reported')"
  },
  "subjective": "2-4 sentence narrative of the patient's reported symptoms, functional limitations, and goals. Written in clinical letter prose.",
  "objective_findings": [
    "Bullet point of an objective finding (e.g., 'Active shoulder flexion limited to 150° vs. 175° on uninvolved side')",
    "Another bullet point",
    "etc."
  ],
  "red_flags_screened": "Brief statement of red flags screened and ruled out (e.g., 'No progressive weakness, no bowel/bladder changes, no unexplained weight loss, no night pain unrelieved by position change.')",
  "assessment": "2-4 sentence clinical assessment / working diagnosis. Use ICF/movement-based language where appropriate.",
  "short_term_goals": [
    "Goal achievable in 4 weeks (functional, measurable)",
    "Another short-term goal",
    "etc. — typically 2-4 goals"
  ],
  "long_term_goals": [
    "Goal achievable in 12 weeks (functional, measurable)",
    "Another long-term goal",
    "etc. — typically 2-4 goals"
  ],
  "plan_of_care": {
    "frequency": "Recommended frequency (e.g., '1-2x/week')",
    "duration": "Recommended duration (e.g., '8-12 weeks')",
    "interventions": [
      "Manual therapy",
      "Therapeutic exercise",
      "Neuromuscular re-education",
      "Patient education and self-management",
      "etc. — only list what's clinically appropriate"
    ]
  },
  "physician_communication_request": "1-2 sentence statement of what we'd like from the physician (typically 'We will continue to update you on the patient's progress. Please contact our office with any questions or if you would like additional information.').",
  "confidence": "high | medium | low",
  "confidence_notes": "If medium or low, briefly explain what was unclear in the transcript."
}`;

async function generateLetterDraftWithClaude(transcript, patientFirstName, patientLastName, evaluatingPT) {
  const userMessage = `PATIENT NAME: ${patientFirstName} ${patientLastName}
EVALUATING PHYSICAL THERAPIST: ${evaluatingPT}

TRANSCRIPT:
${transcript}`;

  const response = await axios.post(
    'https://api.anthropic.com/v1/messages',
    {
      model: 'claude-sonnet-4-6',
      max_tokens: 3000,
      system: [{ type: 'text', text: LETTER_GENERATION_PROMPT }],
      messages: [{ role: 'user', content: userMessage }]
    },
    {
      headers: {
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'Content-Type': 'application/json'
      },
      timeout: 90000
    }
  );

  const text = response.data.content[0].text;
  return JSON.parse(text.replace(/```json|```/g, '').trim());
}

// ─── PDF RENDERING ───────────────────────────────────────────────────────────

function buildLetterHTML(draft) {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const ptName = draft.evaluating_pt || '';
  const ptCreds = PT_CREDENTIALS[ptName] || 'PT, DPT';
  const ptLicense = PT_LICENSES[ptName] || 'PT-PENDING';

  const c = draft.clinical_content || {};
  const ps = c.patient_summary || {};
  const poc = c.plan_of_care || {};
  const md = draft.physician_routing || {};

  const recipientBlock = md.physician_name
    ? `${md.physician_name}${md.physician_practice ? '<br>' + md.physician_practice : ''}${md.physician_fax ? '<br>Fax: ' + md.physician_fax : ''}`
    : '[Physician Name Pending]';

  const salutationName = md.physician_name
    ? 'Dr. ' + (md.physician_name.split(' ').slice(-1)[0] || 'Physician')
    : 'Physician';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page { size: letter; margin: 0.5in 0.6in 0.5in 0.6in; }
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11pt; line-height: 1.45; color: #000000; margin: 0; padding: 0; }
  .letterhead { border-bottom: 3pt solid #FFD70A; padding-bottom: 14pt; margin-bottom: 20pt; display: table; width: 100%; }
  .letterhead-left { display: table-cell; vertical-align: top; width: 60%; }
  .letterhead-right { display: table-cell; vertical-align: top; width: 40%; text-align: right; font-size: 9.5pt; color: #232323; }
  .clinic-name { font-size: 18pt; font-weight: 700; color: #232323; margin: 0 0 2pt 0; letter-spacing: 0.3pt; }
  .clinic-tagline { font-size: 9pt; color: #4b5563; margin: 0; text-transform: uppercase; letter-spacing: 1pt; }
  .meta-line { margin: 1pt 0; }
  .date-line { margin: 0 0 14pt 0; font-size: 11pt; }
  .recipient { margin: 0 0 14pt 0; line-height: 1.4; }
  .re-line { margin: 0 0 16pt 0; font-weight: 700; font-size: 11pt; }
  .salutation { margin: 0 0 12pt 0; }
  .section-heading { font-weight: 700; margin: 14pt 0 4pt 0; color: #232323; font-size: 11pt; border-bottom: 0.5pt solid #cccccc; padding-bottom: 2pt; }
  .section-body { margin: 0 0 6pt 0; }
  ul.findings { margin: 4pt 0 6pt 0; padding-left: 20pt; }
  ul.findings li { margin-bottom: 3pt; }
  .poc-table { margin: 6pt 0 8pt 0; width: 100%; border-collapse: collapse; }
  .poc-table td { padding: 3pt 0; vertical-align: top; }
  .poc-table td.poc-label { width: 110pt; font-weight: 600; }
  .signature-block { margin-top: 28pt; page-break-inside: avoid; }
  .signature-line { border-top: 0.5pt solid #232323; width: 280pt; margin-top: 36pt; padding-top: 4pt; font-size: 10pt; }
  .signature-name { font-weight: 700; font-size: 11pt; }
  .e-attestation { margin-top: 6pt; font-size: 8.5pt; color: #4b5563; font-style: italic; }
  .footer { margin-top: 30pt; padding-top: 8pt; border-top: 0.5pt solid #cccccc; font-size: 8pt; color: #4b5563; text-align: center; }
</style>
</head>
<body>

<div class="letterhead">
  <div class="letterhead-left">
    <p class="clinic-name">${CLINIC.name}</p>
    <p class="clinic-tagline">Outpatient Physical Therapy &middot; Pasadena, CA</p>
  </div>
  <div class="letterhead-right">
    <div class="meta-line">${CLINIC.addr1}</div>
    <div class="meta-line">${CLINIC.addr2}</div>
    <div class="meta-line">P: ${CLINIC.phone} &nbsp;&middot;&nbsp; F: ${CLINIC.fax}</div>
    <div class="meta-line">NPI: ${CLINIC.npi}</div>
    <div class="meta-line">${CLINIC.website}</div>
  </div>
</div>

<div class="date-line">${today}</div>
<div class="recipient">${recipientBlock}</div>
<div class="re-line">RE: ${draft.patient_first_name || ''} ${draft.patient_last_name || ''} &nbsp;&middot;&nbsp; Initial Physical Therapy Evaluation Summary</div>
<div class="salutation">Dear ${salutationName},</div>

<div class="section-body">
This letter is to inform you that your patient, ${draft.patient_first_name || ''} ${draft.patient_last_name || ''}, has been evaluated at our clinic and has begun a course of physical therapy care under our team. The findings, assessment, and recommended plan of care are summarized below for your records.
</div>

<div class="section-heading">Patient Summary</div>
<table class="poc-table">
  <tr><td class="poc-label">Chief Complaint:</td><td>${ps.chief_complaint || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Onset:</td><td>${ps.onset || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Aggravating Factors:</td><td>${ps.aggravating_factors || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Relieving Factors:</td><td>${ps.relieving_factors || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Prior Treatment:</td><td>${ps.prior_treatment || 'None reported'}</td></tr>
</table>

<div class="section-heading">Subjective</div>
<div class="section-body">${c.subjective || ''}</div>

<div class="section-heading">Objective Findings</div>
<ul class="findings">
${(c.objective_findings || []).map(f => `  <li>${f}</li>`).join('\n')}
</ul>

<div class="section-heading">Red Flag Screening</div>
<div class="section-body">${c.red_flags_screened || 'Standard red flag screening completed.'}</div>

<div class="section-heading">Clinical Assessment</div>
<div class="section-body">${c.assessment || ''}</div>

<div class="section-heading">Short-Term Goals (4 weeks)</div>
<ul class="findings">
${(c.short_term_goals || []).map(g => `  <li>${g}</li>`).join('\n')}
</ul>

<div class="section-heading">Long-Term Goals (12 weeks)</div>
<ul class="findings">
${(c.long_term_goals || []).map(g => `  <li>${g}</li>`).join('\n')}
</ul>

<div class="section-heading">Recommended Plan of Care</div>
<table class="poc-table">
  <tr><td class="poc-label">Frequency:</td><td>${poc.frequency || ''}</td></tr>
  <tr><td class="poc-label">Duration:</td><td>${poc.duration || ''}</td></tr>
  <tr><td class="poc-label">Interventions:</td><td>${(poc.interventions || []).join('; ')}</td></tr>
</table>

<div class="section-body" style="margin-top:14pt;">${c.physician_communication_request || 'We will continue to update you on the patient\'s progress. Please contact our office with any questions or if you would like additional information.'}</div>

<div class="signature-block">
  <div>Sincerely,</div>
  <div class="signature-line">
    <div class="signature-name">${ptName}, ${ptCreds}</div>
    <div>CA PT License #: ${ptLicense}</div>
  </div>
  <div class="e-attestation">
    Electronically reviewed and approved by ${ptName}, ${ptCreds} &middot; License ${ptLicense} &middot; on ${draft.pt_approved_at_human || today}
  </div>
</div>

<div class="footer">
  This communication contains confidential health information protected under HIPAA. If you are not the intended recipient, please notify our office immediately and destroy this document.
</div>

</body>
</html>`;
}

async function renderLetterPDF(draft) {
  const puppeteer = require('puppeteer-core');
  const chromium = require('@sparticuz/chromium');

  const html = buildLetterHTML(draft);

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: true
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    return await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: { top: '0.5in', bottom: '0.5in', left: '0.6in', right: '0.6in' }
    });
  } finally {
    await browser.close();
  }
}

// ─── GOOGLE WORKSPACE: DRIVE, SHEETS, GMAIL ──────────────────────────────────

function getServiceAccountAuth(scopes) {
  const SERVICE_ACCOUNT_JSON = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '{}');
  return new google.auth.GoogleAuth({ credentials: SERVICE_ACCOUNT_JSON, scopes });
}

async function uploadLetterPDFToDrive(pdfBuffer, filename) {
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/drive']);
  const drive = google.drive({ version: 'v3', auth });

  const stream = new Readable();
  stream.push(pdfBuffer);
  stream.push(null);

  const file = await drive.files.create({
    requestBody: {
      name: filename,
      parents: [PHYSICIAN_LETTERS_DRIVE_FOLDER],
      mimeType: 'application/pdf'
    },
    media: { mimeType: 'application/pdf', body: stream },
    fields: 'id, webViewLink',
    supportsAllDrives: true
  });

  return { id: file.data.id, webViewLink: file.data.webViewLink };
}

async function appendLetterAuditRow(rowValues) {
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/spreadsheets']);
  const sheets = google.sheets({ version: 'v4', auth });

  await sheets.spreadsheets.values.append({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!A:O`,
    valueInputOption: 'USER_ENTERED',
    insertDataOption: 'INSERT_ROWS',
    requestBody: { values: [rowValues] }
  });
}

async function updateLetterAuditRow(letterId, columnUpdates) {
  // columnUpdates: { K: 'value', L: 'value' } — column-letter -> value
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/spreadsheets']);
  const sheets = google.sheets({ version: 'v4', auth });

  // Find the row with this letter ID (column B)
  const lookup = await sheets.spreadsheets.values.get({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!B:B`
  });
  const rows = lookup.data.values || [];
  let rowIndex = -1;
  for (let i = 0; i < rows.length; i++) {
    if (rows[i][0] === letterId) { rowIndex = i + 1; break; }
  }
  if (rowIndex === -1) {
    console.warn(`[letter-audit] Letter ID ${letterId} not found in sheet — skipping update`);
    return;
  }

  const data = Object.entries(columnUpdates).map(([col, val]) => ({
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!${col}${rowIndex}`,
    values: [[val]]
  }));

  await sheets.spreadsheets.values.batchUpdate({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    requestBody: { valueInputOption: 'USER_ENTERED', data }
  });
}

async function sendWeeklyLetterAuditEmail() {
  try {
    const drafts = listLetterDrafts();
    const oneWeekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = drafts.filter(d => new Date(d.created_at).getTime() >= oneWeekAgo);

    if (recent.length === 0) {
      console.log('[letter-audit] No letters in the past week — skipping weekly email');
      return;
    }

    const byStatus = {};
    recent.forEach(d => { byStatus[d.status] = (byStatus[d.status] || 0) + 1; });

    const statusRows = Object.entries(byStatus).map(([status, count]) =>
      `<tr><td style="padding:6px 12px; border:1px solid #e5e7eb;">${status}</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${count}</td></tr>`
    ).join('');

    const detailRows = recent.map(d => `<tr>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${patientInitials(d)}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.evaluating_pt}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.status}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.physician_routing?.physician_name || '—'}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.faxed_at ? new Date(d.faxed_at).toLocaleDateString() : '—'}</td>
    </tr>`).join('');

    const html = `<!DOCTYPE html>
<html><body style="font-family:'Helvetica',Arial,sans-serif; max-width:680px; margin:0 auto; padding:20px; color:#232323;">
<div style="background:#232323; color:#fff; padding:18px; border-radius:10px;">
  <h2 style="margin:0;">Physician Letter Audit — Weekly Summary</h2>
  <p style="margin:6px 0 0 0; opacity:0.85; font-size:13px;">Week ending ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
</div>
<h3 style="margin-top:24px;">Status Breakdown</h3>
<table style="border-collapse:collapse; font-size:14px;">
  <thead><tr style="background:#F7F8FA;"><th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Status</th><th style="padding:6px 12px; text-align:right; border:1px solid #e5e7eb;">Count</th></tr></thead>
  <tbody>${statusRows}</tbody>
</table>
<h3 style="margin-top:24px;">Letter Detail (${recent.length} total)</h3>
<table style="border-collapse:collapse; font-size:13px; width:100%;">
  <thead><tr style="background:#F7F8FA;">
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Patient</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">PT</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Status</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">MD</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Faxed</th>
  </tr></thead>
  <tbody>${detailRows}</tbody>
</table>
<p style="margin-top:24px; font-size:12px; color:#4b5563;">Full audit log: <a href="https://docs.google.com/spreadsheets/d/${PHYSICIAN_LETTERS_SHEET_ID}/edit">Physician Letter Audit Log</a></p>
</body></html>`;

    const SERVICE_ACCOUNT_JSON = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '{}');
    const auth = new google.auth.JWT(
      SERVICE_ACCOUNT_JSON.client_email,
      null,
      SERVICE_ACCOUNT_JSON.private_key,
      ['https://www.googleapis.com/auth/gmail.send'],
      'jordan@movementclinicpt.com'
    );
    const gmail = google.gmail({ version: 'v1', auth });

    const subject = `Physician Letter Audit — Week of ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`;
    const messageParts = [
      'From: jordan@movementclinicpt.com',
      'To: jordan@movementclinicpt.com',
      `Subject: ${subject}`,
      'MIME-Version: 1.0',
      'Content-Type: text/html; charset=utf-8',
      '',
      html
    ];
    const rawMessage = Buffer.from(messageParts.join('\r\n')).toString('base64')
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    await gmail.users.messages.send({ userId: 'me', requestBody: { raw: rawMessage } });
    console.log('[letter-audit] Weekly email sent to Jordan');
  } catch (err) {
    console.error('[letter-audit] Weekly email failed:', err.message);
  }
}

// ─── SLACK NOTIFICATIONS ─────────────────────────────────────────────────────
// All messages are HIPAA-safe — patient initials only, no clinical content,
// no fax numbers. PHI lives in Drive (auth-gated) and the audit sheet.

// Posts a Slack message and returns its `ts` (timestamp ID, used to react/reply later).
// Pass `thread_ts` to post as a threaded reply under an existing message.
async function postSlack(channel, text, blocks, thread_ts) {
  const payload = { channel, text, blocks };
  if (thread_ts) payload.thread_ts = thread_ts;
  const response = await axios.post(
    'https://slack.com/api/chat.postMessage',
    payload,
    { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } }
  );
  if (!response.data.ok) {
    console.warn(`[letter-notify] Slack post failed: ${response.data.error}`);
    return null;
  }
  return response.data.ts;
}

// Add a ✅ (or other) emoji reaction to a Slack message.
// Silent failure if message_ts is missing or Slack rejects (e.g., already reacted).
async function addReaction(channel, message_ts, emoji = 'white_check_mark') {
  if (!channel || !message_ts || !SLACK_BOT_TOKEN) return;
  try {
    const response = await axios.post(
      'https://slack.com/api/reactions.add',
      { channel, timestamp: message_ts, name: emoji },
      { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } }
    );
    if (!response.data.ok && response.data.error !== 'already_reacted') {
      console.warn(`[letter-notify] Reaction add failed: ${response.data.error}`);
    }
  } catch (err) {
    console.warn(`[letter-notify] Reaction add error: ${err.message}`);
  }
}

// Posts the top-level "ready for review" message to #physician-letters channel.
// @-mentions the evaluating PT (so they get a personal Slack notification).
// Returns the message ts so the caller can save it on the draft for later
// reactions and threaded replies.
async function notifyPTForReview(token, draft) {
  const ptName = draft.evaluating_pt;
  const ptSlackId = PT_SLACK_IDS[ptName];
  const reviewUrl = `${BASE_URL}/eval-letter/${token}`;
  const initials = patientInitials(draft);
  const ptMention = ptSlackId ? `<@${ptSlackId}>` : (ptName || 'PT');

  if (!ptSlackId) {
    console.warn(`[letter-notify] No Slack ID for PT "${ptName}" — channel post will use plaintext name instead of @-mention`);
  }

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, `Evaluation summary ready for review — ${initials} converted to Package Purchased`, [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:clipboard: *Evaluation Summary Ready for Review — ${initials}*\n\n${ptMention} please review the AI-drafted evaluation summary that will be sent to this patient's physician.` }
    },
    {
      type: 'actions',
      elements: [{ type: 'button', text: { type: 'plain_text', text: 'Review Summary →' }, url: reviewUrl, style: 'primary' }]
    }
  ]);
}

// Posts as a threaded reply to the original PT review message.
// Returns the new message ts so the caller can save it on the draft for later reactions.
async function notifyAdminForRouting(token, draft) {
  const adminUrl = `${BASE_URL}/eval-letter/${token}/admin`;
  const initials = patientInitials(draft);
  const threadTs = draft.slack_pt_review_ts || null;

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, 'New evaluation summary ready for fax routing', [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:fax: *Ready for Fax Routing — ${initials}*\n\nPT has approved. Admin team — please add the physician name + fax number to generate the PDF for faxing.` }
    },
    {
      type: 'actions',
      elements: [{ type: 'button', text: { type: 'plain_text', text: 'Add MD Info & Generate PDF →' }, url: adminUrl, style: 'primary' }]
    }
  ], threadTs);
}

// Posts as a threaded reply to the original PT review message.
// Returns the new message ts so the caller can save it on the draft for later reactions.
async function notifyAdminPDFReady(token, draft, driveLink) {
  const initials = patientInitials(draft);
  const adminUrl = `${BASE_URL}/eval-letter/${token}/admin`;
  const threadTs = draft.slack_pt_review_ts || null;

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, 'PDF ready to fax', [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:page_facing_up: *PDF Ready to Fax — ${initials}*\n\nFax it from your fax workflow, then come back here and click *Mark as Faxed*.` }
    },
    {
      type: 'actions',
      elements: [
        { type: 'button', text: { type: 'plain_text', text: 'Open in Drive' }, url: driveLink },
        { type: 'button', text: { type: 'plain_text', text: 'Mark as Faxed' }, url: adminUrl, style: 'primary' }
      ]
    }
  ], threadTs);
}

async function notifyJordanOfError(errorMsg, patientName) {
  const jordanId = process.env.PT_SLACK_JORDAN;
  if (!jordanId || !SLACK_BOT_TOKEN) return;
  try {
    await axios.post('https://slack.com/api/chat.postMessage', {
      channel: jordanId,
      text: `:warning: Physician letter generation failed for ${patientName}: ${errorMsg}`
    }, { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } });
  } catch (err) {
    console.error('[letter-notify] Failed to notify Jordan:', err.message);
  }
}

// ─── ORCHESTRATOR (PUBLIC ENTRY POINTS) ──────────────────────────────────────
// These are what the post-eval handler calls. Everything else above is internal.

// Called when outcome=Converted AND PT chose NOT to generate a physician letter.
// Posts a "no letter needed" notification to the channel and logs an audit row
// with status 'letter_skipped' so we have a complete record of every converted
// patient (whether or not a letter was sent).
//
// Reasons a PT might skip:
//   - Patient is self-referred (no physician to fax)
//   - Patient declined physician communication
//   - Physician already informed via another channel (existing relationship, etc.)
//
// This function does NOT call Claude (no PHI sent to Anthropic, saves cost).
// No Drive upload, no PDF generation. Just: Slack post + audit row.
async function notifyPhysicianLetterSkipped(opts) {
  const {
    patient_first_name,
    patient_last_name,
    evaluating_pt,
    contact_id,
    ghl_opportunity_id
  } = opts;

  try {
    console.log(`[letter] Letter skipped for ${patient_first_name} ${patient_last_name} (PT: ${evaluating_pt})`);

    const initials = `${(patient_first_name || '?')[0]}.${(patient_last_name || '?')[0]}.`;

    // Post non-actionable notification to channel — no @-mention, no buttons,
    // no thread (this is a terminal event for this patient's letter workflow).
    await postSlack(PHYSICIAN_LETTERS_CHANNEL, `No physician letter needed — ${initials}`, [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `:no_entry_sign: *No Physician Letter — ${initials}*\n\n${initials} has converted to Package Purchased. The evaluating PT (*${evaluating_pt}*) chose not to generate a physician letter for this patient.\n\n_Typically this means the patient is self-referred, declined physician communication, or the physician was informed through another channel. No action needed from admin._`
        }
      }
    ]);

    // Audit row — status 'letter_skipped' so the data is filterable.
    // Uses the same 15-column schema as the regular workflow.
    const skipToken = generateLetterToken();  // unique ID for this skip event
    await appendLetterAuditRow([
      new Date().toISOString(),         // A: Timestamp
      skipToken,                         // B: Letter ID (skip event ID)
      evaluating_pt,                     // C: PT
      initials,                          // D: Patient Initials
      'letter_skipped',                  // E: Status
      '',                                // F: PT Approved At
      '',                                // G: MD Name
      '',                                // H: MD Practice
      '',                                // I: MD Fax
      '',                                // J: Admin Routed By
      '',                                // K: Admin Routed At
      '',                                // L: Faxed By
      '',                                // M: Faxed At
      '',                                // N: Drive Link
      'PT chose not to generate physician letter at submission time'  // O: Notes
    ]);

    console.log(`[letter] Skip event logged — token ${skipToken}`);
  } catch (err) {
    console.error('[letter] Skip notification failed:', err.message);
    // Non-blocking — failure here doesn't prevent the patient's eval from being processed.
    // Just log; no PT DM needed for this since it's a notification-only path.
  }
}

async function generateAndQueuePhysicianLetter(opts) {
  const {
    transcript,
    patient_first_name,
    patient_last_name,
    patient_phone,
    patient_email,
    evaluating_pt,
    contact_id,
    ghl_opportunity_id
  } = opts;

  try {
    console.log(`[letter] Generating physician letter draft for ${patient_first_name} ${patient_last_name}`);
    const clinicalContent = await generateLetterDraftWithClaude(
      transcript,
      patient_first_name,
      patient_last_name,
      evaluating_pt
    );

    const token = generateLetterToken();
    const draft = {
      token,
      letter_id: token,
      created_at: new Date().toISOString(),
      patient_first_name,
      patient_last_name,
      patient_phone,
      patient_email,
      evaluating_pt,
      ghl_contact_id: contact_id,
      ghl_opportunity_id,
      status: 'pending_pt_review',
      clinical_content: clinicalContent,
      physician_routing: null,
      pt_approved_at: null,
      pt_approved_at_human: null,
      pdf_drive_id: null,
      pdf_drive_link: null,
      faxed_at: null,
      faxed_by: null,
      admin_routed_by: null,
      admin_routed_at: null,
      // Slack message timestamps — used for threaded replies and ✅ reactions
      slack_pt_review_ts: null,
      slack_admin_routing_ts: null,
      slack_pdf_ready_ts: null
    };

    saveLetterDraft(token, draft);

    // Post the top-level review message and save its ts for later threading + reactions
    const ptReviewTs = await notifyPTForReview(token, draft);
    if (ptReviewTs) {
      draft.slack_pt_review_ts = ptReviewTs;
      saveLetterDraft(token, draft);
    }

    // Initial audit log row
    await appendLetterAuditRow([
      new Date().toISOString(),               // A: Timestamp
      token,                                   // B: Letter ID
      evaluating_pt,                           // C: PT
      patientInitials(draft),                  // D: Patient Initials
      'pending_pt_review',                     // E: Status
      '',                                      // F: PT Approved At
      '',                                      // G: MD Name
      '',                                      // H: MD Practice
      '',                                      // I: MD Fax
      '',                                      // J: Admin Routed By
      '',                                      // K: Admin Routed At
      '',                                      // L: Faxed By
      '',                                      // M: Faxed At
      '',                                      // N: Drive Link
      `Confidence: ${clinicalContent.confidence || 'unknown'}`  // O: Notes
    ]);

    console.log(`[letter] Draft created — token ${token}`);
  } catch (err) {
    console.error('[letter] Generation failed:', err.message);
    await notifyJordanOfError(err.message, `${patient_first_name} ${patient_last_name}`);
  }
}

// ─── HTML VIEW: PT REVIEW PAGE ───────────────────────────────────────────────

function renderPTReviewPage(draft) {
  const c = draft.clinical_content || {};
  const ps = c.patient_summary || {};
  const poc = c.plan_of_care || {};
  const initials = patientInitials(draft);
  const isApproved = draft.status !== 'pending_pt_review';
  const confColor = c.confidence === 'high' ? '#1F7A4D' : c.confidence === 'medium' ? '#B85C00' : '#A02020';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Evaluation Summary Review — ${initials}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Montserrat', sans-serif; background: #F7F8FA; color: #232323; margin: 0; padding: 0; padding-top: env(safe-area-inset-top); }
  .header { background: #232323; color: #fff; padding: 18px 20px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
  .header .sub { margin-top: 4px; font-size: 13px; opacity: 0.85; }
  .container { max-width: 760px; margin: 0 auto; padding: 16px; }
  .conf-banner { background: #fff; border-left: 5px solid ${confColor}; border-radius: 8px; padding: 14px 16px; margin-bottom: 16px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .conf-label { font-weight: 700; color: ${confColor}; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
  .conf-notes { font-size: 13px; margin-top: 6px; color: #555; }
  .card { background: #fff; border-radius: 10px; padding: 16px; margin-bottom: 14px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .card h3 { margin: 0 0 10px 0; font-size: 14px; font-weight: 700; color: #232323; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
  label.field-label { display: block; font-size: 12px; font-weight: 600; color: #4b5563; margin: 8px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
  textarea, input[type="text"] { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 14px; border: 1px solid #d8dde5; border-radius: 8px; padding: 10px 12px; background: #fff; color: #232323; }
  textarea { min-height: 60px; resize: vertical; }
  textarea.tall { min-height: 120px; }
  .bullet-list { display: flex; flex-direction: column; gap: 6px; }
  .bullet-row { display: flex; gap: 6px; align-items: flex-start; }
  .bullet-row textarea { flex: 1; min-height: 38px; }
  .bullet-remove { background: #f3f4f6; color: #4b5563; border: none; border-radius: 6px; padding: 0 10px; cursor: pointer; font-weight: 700; font-size: 16px; }
  .add-bullet { background: #f3f4f6; color: #4b5563; border: none; border-radius: 6px; padding: 8px 12px; font-family: 'Montserrat', sans-serif; font-weight: 600; font-size: 13px; margin-top: 6px; cursor: pointer; }
  .attestation { background: #fffbe5; border: 1px solid #FFD70A; border-radius: 10px; padding: 14px 16px; margin: 16px 0; }
  .attestation label { display: flex; gap: 12px; align-items: flex-start; cursor: pointer; user-select: none; }
  .attestation input[type="checkbox"] { width: 22px; height: 22px; margin-top: 2px; flex-shrink: 0; }
  .attestation-text { font-size: 13px; line-height: 1.5; }
  .approve-btn { background: #FFD70A; color: #232323; border: none; border-radius: 10px; padding: 16px 20px; width: 100%; font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 16px; cursor: pointer; margin-top: 8px; }
  .approve-btn:disabled { background: #e5e7eb; color: #9ca3af; cursor: not-allowed; }
  .approved-banner { background: #1F7A4D; color: #fff; padding: 16px; border-radius: 10px; text-align: center; font-weight: 600; }
  .status-msg { padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 14px; display: none; }
  .status-msg.error { background: #fde8e8; color: #A02020; }
  .status-msg.success { background: #e7f5ed; color: #1F7A4D; }
  .row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  @media (max-width: 600px) { .row { grid-template-columns: 1fr; } }
</style>
</head>
<body>

<div class="header">
  <h1>Evaluation Summary Review</h1>
  <div class="sub">Patient: ${initials} &middot; Evaluating PT: ${draft.evaluating_pt}</div>
</div>

<div class="container">

  ${isApproved ? `<div class="approved-banner">✓ This summary has been approved and is now in the admin queue for routing.</div>` : ''}

  <div class="conf-banner">
    <div class="conf-label">Claude Confidence: ${c.confidence || 'unknown'}</div>
    ${c.confidence_notes ? `<div class="conf-notes">${c.confidence_notes}</div>` : ''}
  </div>

  <form id="reviewForm" ${isApproved ? 'style="opacity:0.6; pointer-events:none;"' : ''}>

    <div class="card">
      <h3>Patient Summary</h3>
      <label class="field-label">Chief Complaint</label>
      <textarea name="chief_complaint">${ps.chief_complaint || ''}</textarea>
      <label class="field-label">Onset</label>
      <textarea name="onset">${ps.onset || ''}</textarea>
      <label class="field-label">Aggravating Factors</label>
      <textarea name="aggravating_factors">${ps.aggravating_factors || ''}</textarea>
      <label class="field-label">Relieving Factors</label>
      <textarea name="relieving_factors">${ps.relieving_factors || ''}</textarea>
      <label class="field-label">Prior Treatment</label>
      <textarea name="prior_treatment">${ps.prior_treatment || ''}</textarea>
    </div>

    <div class="card">
      <h3>Subjective</h3>
      <textarea name="subjective" class="tall">${c.subjective || ''}</textarea>
    </div>

    <div class="card">
      <h3>Objective Findings</h3>
      <div class="bullet-list" id="objective_findings_list">
        ${(c.objective_findings || []).map(f => `<div class="bullet-row"><textarea data-bullet="objective_findings">${f}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('objective_findings_list', 'objective_findings')">+ Add finding</button>
    </div>

    <div class="card">
      <h3>Red Flag Screening</h3>
      <textarea name="red_flags_screened" class="tall">${c.red_flags_screened || ''}</textarea>
    </div>

    <div class="card">
      <h3>Clinical Assessment</h3>
      <textarea name="assessment" class="tall">${c.assessment || ''}</textarea>
    </div>

    <div class="card">
      <h3>Short-Term Goals (4 weeks)</h3>
      <div class="bullet-list" id="short_term_goals_list">
        ${(c.short_term_goals || []).map(g => `<div class="bullet-row"><textarea data-bullet="short_term_goals">${g}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('short_term_goals_list', 'short_term_goals')">+ Add goal</button>
    </div>

    <div class="card">
      <h3>Long-Term Goals (12 weeks)</h3>
      <div class="bullet-list" id="long_term_goals_list">
        ${(c.long_term_goals || []).map(g => `<div class="bullet-row"><textarea data-bullet="long_term_goals">${g}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('long_term_goals_list', 'long_term_goals')">+ Add goal</button>
    </div>

    <div class="card">
      <h3>Plan of Care</h3>
      <div class="row">
        <div><label class="field-label">Frequency</label><input type="text" name="frequency" value="${poc.frequency || ''}"></div>
        <div><label class="field-label">Duration</label><input type="text" name="duration" value="${poc.duration || ''}"></div>
      </div>
      <label class="field-label" style="margin-top:8px;">Interventions</label>
      <div class="bullet-list" id="interventions_list">
        ${(poc.interventions || []).map(intv => `<div class="bullet-row"><textarea data-bullet="interventions">${intv}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('interventions_list', 'interventions')">+ Add intervention</button>
    </div>

    <div class="card">
      <h3>Communication to Physician</h3>
      <textarea name="physician_communication_request" class="tall">${c.physician_communication_request || ''}</textarea>
    </div>

    <div class="attestation">
      <label>
        <input type="checkbox" id="attest_check" required>
        <div class="attestation-text">
          I have reviewed this evaluation summary and confirm that it accurately reflects the patient's clinical presentation, my assessment, and my recommended plan of care. I approve it for transmission to the patient's referring physician under my electronic signature as ${draft.evaluating_pt}, ${PT_CREDENTIALS[draft.evaluating_pt] || 'PT, DPT'} (CA PT License: ${PT_LICENSES[draft.evaluating_pt] || 'PT-PENDING'}).
        </div>
      </label>
    </div>

    <button type="button" class="approve-btn" id="approveBtn" disabled onclick="approveLetter()">Approve & Send to Admin</button>
    <div class="status-msg" id="statusMsg"></div>

  </form>

</div>

<script>
function addBullet(listId, name) {
  const list = document.getElementById(listId);
  const row = document.createElement('div');
  row.className = 'bullet-row';
  row.innerHTML = '<textarea data-bullet="' + name + '"></textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button>';
  list.appendChild(row);
  row.querySelector('textarea').focus();
}
function removeBullet(btn) { btn.parentElement.remove(); }

document.getElementById('attest_check')?.addEventListener('change', e => {
  document.getElementById('approveBtn').disabled = !e.target.checked;
});

function collectBullets(name) {
  return Array.from(document.querySelectorAll('textarea[data-bullet="' + name + '"]'))
    .map(el => el.value.trim()).filter(Boolean);
}

async function approveLetter() {
  const btn = document.getElementById('approveBtn');
  const status = document.getElementById('statusMsg');
  btn.disabled = true;
  btn.textContent = 'Submitting...';

  const payload = {
    clinical_content: {
      patient_summary: {
        chief_complaint: document.querySelector('[name="chief_complaint"]').value,
        onset: document.querySelector('[name="onset"]').value,
        aggravating_factors: document.querySelector('[name="aggravating_factors"]').value,
        relieving_factors: document.querySelector('[name="relieving_factors"]').value,
        prior_treatment: document.querySelector('[name="prior_treatment"]').value
      },
      subjective: document.querySelector('[name="subjective"]').value,
      objective_findings: collectBullets('objective_findings'),
      red_flags_screened: document.querySelector('[name="red_flags_screened"]').value,
      assessment: document.querySelector('[name="assessment"]').value,
      short_term_goals: collectBullets('short_term_goals'),
      long_term_goals: collectBullets('long_term_goals'),
      plan_of_care: {
        frequency: document.querySelector('[name="frequency"]').value,
        duration: document.querySelector('[name="duration"]').value,
        interventions: collectBullets('interventions')
      },
      physician_communication_request: document.querySelector('[name="physician_communication_request"]').value
    }
  };

  try {
    const res = await fetch('/eval-letter/${draft.token}/approve', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.style.display = 'block';
      status.textContent = '✓ Approved. Admin team has been notified to add physician routing info.';
      btn.textContent = '✓ Approved';
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Error: ' + err.message;
    btn.disabled = false;
    btn.textContent = 'Approve & Send to Admin';
  }
}
</script>

</body>
</html>`;
}

// ─── HTML VIEW: ADMIN ROUTING PAGE ───────────────────────────────────────────

function renderAdminRoutingPage(draft) {
  const initials = patientInitials(draft);
  const md = draft.physician_routing || {};
  const isFaxed = draft.status === 'faxed';
  const pdfReady = draft.pdf_drive_link && !isFaxed;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Admin Routing — ${initials}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Montserrat', sans-serif; background: #F7F8FA; color: #232323; margin: 0; padding-top: env(safe-area-inset-top); }
  .header { background: #232323; color: #fff; padding: 18px 20px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
  .header .sub { margin-top: 4px; font-size: 13px; opacity: 0.85; }
  .container { max-width: 600px; margin: 0 auto; padding: 16px; }
  .card { background: #fff; border-radius: 10px; padding: 18px; margin-bottom: 14px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .card h3 { margin: 0 0 12px 0; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; color: #232323; }
  label { display: block; font-size: 12px; font-weight: 600; color: #4b5563; margin: 10px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
  input[type="text"] { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 15px; border: 1px solid #d8dde5; border-radius: 8px; padding: 12px; }
  .btn-primary { background: #0065a3; color: #fff; border: none; border-radius: 10px; padding: 14px 20px; width: 100%; font-family: 'Montserrat', sans-serif; font-weight: 600; font-size: 15px; cursor: pointer; margin-top: 8px; }
  .btn-primary:disabled { background: #e5e7eb; color: #9ca3af; cursor: not-allowed; }
  .btn-yellow { background: #FFD70A; color: #232323; }
  .btn-success { background: #1F7A4D; }
  .pdf-link { display: block; padding: 12px; background: #F7F8FA; border-radius: 8px; margin: 10px 0; color: #0065a3; text-decoration: none; text-align: center; font-weight: 600; }
  .status-msg { padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 14px; display: none; }
  .status-msg.error { background: #fde8e8; color: #A02020; }
  .status-msg.success { background: #e7f5ed; color: #1F7A4D; }
  .info-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
  .info-row:last-child { border-bottom: none; }
  .info-label { color: #4b5563; font-weight: 600; }
  .faxed-banner { background: #1F7A4D; color: #fff; padding: 16px; border-radius: 10px; text-align: center; font-weight: 600; }
</style>
</head>
<body>

<div class="header">
  <h1>Physician Letter Routing</h1>
  <div class="sub">Patient: ${initials} &middot; PT: ${draft.evaluating_pt}</div>
</div>

<div class="container">

  ${isFaxed ? `<div class="faxed-banner">✓ Faxed by ${draft.faxed_by} on ${new Date(draft.faxed_at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}</div>` : ''}

  <div class="card">
    <h3>Letter Status</h3>
    <div class="info-row"><span class="info-label">Status</span><span>${draft.status}</span></div>
    <div class="info-row"><span class="info-label">PT Approved</span><span>${draft.pt_approved_at_human || '—'}</span></div>
    ${draft.physician_routing ? `
    <div class="info-row"><span class="info-label">MD Name</span><span>${draft.physician_routing.physician_name}</span></div>
    <div class="info-row"><span class="info-label">MD Fax</span><span>${draft.physician_routing.physician_fax}</span></div>
    ` : ''}
  </div>

  ${!isFaxed && !pdfReady && draft.status === 'pending_admin_routing' ? `
  <div class="card">
    <h3>Physician Routing Info</h3>
    <label>Physician Name *</label>
    <input type="text" id="physician_name" value="${md.physician_name || ''}" placeholder="Dr. Jane Smith">
    <label>Physician Practice (optional)</label>
    <input type="text" id="physician_practice" value="${md.physician_practice || ''}" placeholder="Pasadena Family Medicine">
    <label>Fax Number *</label>
    <input type="text" id="physician_fax" value="${md.physician_fax || ''}" placeholder="(626) 555-0123">
    <label>Your Name (admin) *</label>
    <input type="text" id="admin_name" placeholder="Katy / Shane">
    <button type="button" class="btn-primary btn-yellow" onclick="generatePdf()">Generate PDF & Notify Fax Queue</button>
    <div class="status-msg" id="statusMsg"></div>
  </div>` : ''}

  ${pdfReady ? `
  <div class="card">
    <h3>PDF Ready</h3>
    <a href="${draft.pdf_drive_link}" target="_blank" class="pdf-link">📄 Open PDF in Drive</a>
    <p style="font-size:13px; color:#4b5563;">Fax it from your fax workflow, then mark it as faxed below.</p>
    <label>Faxed By *</label>
    <input type="text" id="faxed_by" placeholder="Katy / Shane">
    <button type="button" class="btn-primary btn-success" onclick="markFaxed()">Mark as Faxed</button>
    <div class="status-msg" id="statusMsg2"></div>
  </div>` : ''}

  ${draft.status === 'pending_pt_review' ? `
  <div class="card">
    <h3 style="color:#A02020;">⚠️ Not Ready</h3>
    <p>This letter is still pending PT review. The admin routing step will become available once the PT approves it.</p>
  </div>` : ''}

</div>

<script>
async function generatePdf() {
  const name = document.getElementById('physician_name').value.trim();
  const fax = document.getElementById('physician_fax').value.trim();
  const practice = document.getElementById('physician_practice').value.trim();
  const adminName = document.getElementById('admin_name').value.trim();
  const status = document.getElementById('statusMsg');

  if (!name || !fax || !adminName) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Physician name, fax number, and your name are all required.';
    return;
  }

  status.className = 'status-msg';
  status.style.display = 'block';
  status.style.background = '#F7F8FA';
  status.style.color = '#4b5563';
  status.textContent = 'Generating PDF...';

  try {
    const res = await fetch('/eval-letter/${draft.token}/generate-pdf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ physician_name: name, physician_fax: fax, physician_practice: practice, admin_name: adminName })
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.textContent = '✓ PDF generated. Reloading...';
      setTimeout(() => location.reload(), 1200);
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.textContent = 'Error: ' + err.message;
  }
}

async function markFaxed() {
  const by = document.getElementById('faxed_by').value.trim();
  const status = document.getElementById('statusMsg2');
  if (!by) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Please enter your name.';
    return;
  }
  try {
    const res = await fetch('/eval-letter/${draft.token}/mark-faxed', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ faxed_by: by })
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.style.display = 'block';
      status.textContent = '✓ Marked as faxed. Reloading...';
      setTimeout(() => location.reload(), 1200);
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Error: ' + err.message;
  }
}
</script>

</body>
</html>`;
}

// ─── EXPRESS ROUTES ──────────────────────────────────────────────────────────

router.get('/:token', (req, res) => {
  const draft = loadLetterDraft(req.params.token);
  if (!draft) return res.status(404).send('<h1>Letter not found</h1><p>This letter draft may have expired or been removed.</p>');
  res.send(renderPTReviewPage(draft));
});

router.post('/:token/approve', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });
    if (draft.status !== 'pending_pt_review') {
      return res.status(409).json({ error: 'Letter has already been approved' });
    }

    const { clinical_content } = req.body;
    if (!clinical_content) return res.status(400).json({ error: 'Missing clinical_content' });

    draft.clinical_content = clinical_content;
    draft.status = 'pending_admin_routing';
    draft.pt_approved_at = new Date().toISOString();
    draft.pt_approved_at_human = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    saveLetterDraft(req.params.token, draft);

    await updateLetterAuditRow(req.params.token, {
      'E': 'pending_admin_routing',
      'F': draft.pt_approved_at
    });

    // ✅ react to the top-level PT review message (visual signal of approval)
    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_pt_review_ts);

    // Post the admin routing message as a threaded reply, save its ts
    const adminTs = await notifyAdminForRouting(req.params.token, draft);
    if (adminTs) {
      draft.slack_admin_routing_ts = adminTs;
      saveLetterDraft(req.params.token, draft);
    }

    res.json({ success: true });
  } catch (err) {
    console.error('[letter approve] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

router.get('/:token/admin', (req, res) => {
  const draft = loadLetterDraft(req.params.token);
  if (!draft) return res.status(404).send('<h1>Letter not found</h1>');
  res.send(renderAdminRoutingPage(draft));
});

router.post('/:token/generate-pdf', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });
    if (draft.status !== 'pending_admin_routing') {
      return res.status(409).json({ error: 'Letter is not in pending_admin_routing state (current: ' + draft.status + ')' });
    }

    const { physician_name, physician_fax, physician_practice, admin_name } = req.body;
    if (!physician_name || !physician_fax || !admin_name) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    draft.physician_routing = {
      physician_name,
      physician_fax,
      physician_practice: physician_practice || ''
    };
    draft.admin_routed_by = admin_name;
    draft.admin_routed_at = new Date().toISOString();
    draft.status = 'pdf_ready';

    const pdfBuffer = await renderLetterPDF(draft);

    const dateStr = new Date().toISOString().split('T')[0];
    const cleanLast = (draft.patient_last_name || 'Patient').replace(/[^a-zA-Z0-9]/g, '');
    const cleanFirst = (draft.patient_first_name || '').replace(/[^a-zA-Z0-9]/g, '');
    const filename = `${cleanLast}_${cleanFirst}_${dateStr}.pdf`;

    const driveResult = await uploadLetterPDFToDrive(pdfBuffer, filename);
    draft.pdf_drive_id = driveResult.id;
    draft.pdf_drive_link = driveResult.webViewLink;
    saveLetterDraft(req.params.token, draft);

    await updateLetterAuditRow(req.params.token, {
      'E': 'pdf_ready',
      'G': physician_name,
      'H': physician_practice || '',
      'I': physician_fax,
      'J': admin_name,
      'K': draft.admin_routed_at,
      'N': driveResult.webViewLink
    });

    // ✅ react to the admin routing message (visual signal that PDF was generated)
    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_admin_routing_ts);

    // Post the PDF-ready message as a threaded reply, save its ts
    const pdfReadyTs = await notifyAdminPDFReady(req.params.token, draft, driveResult.webViewLink);
    if (pdfReadyTs) {
      draft.slack_pdf_ready_ts = pdfReadyTs;
      saveLetterDraft(req.params.token, draft);
    }

    res.json({ success: true, drive_link: driveResult.webViewLink });
  } catch (err) {
    console.error('[letter generate-pdf] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

router.post('/:token/mark-faxed', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });

    const { faxed_by } = req.body;
    if (!faxed_by) return res.status(400).json({ error: 'faxed_by required' });

    draft.faxed_by = faxed_by;
    draft.faxed_at = new Date().toISOString();
    draft.status = 'faxed';
    saveLetterDraft(req.params.token, draft);

    await updateLetterAuditRow(req.params.token, {
      'E': 'faxed',
      'L': faxed_by,
      'M': draft.faxed_at
    });

    // ✅ react to the PDF-ready message (visual signal that the letter was actually faxed)
    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_pdf_ready_ts);

    res.json({ success: true });
  } catch (err) {
    console.error('[letter mark-faxed] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ─── INITIALIZATION (CALLED FROM MAIN INDEX.JS) ──────────────────────────────

function init() {
  // Schedule weekly Friday 5pm PT audit email
  setInterval(() => {
    const now = new Date();
    const ptOffset = -8;  // close enough for a weekly trigger window
    const ptHour = (now.getUTCHours() + ptOffset + 24) % 24;
    const ptDay = now.getUTCDay();  // Friday = 5
    const ptMinute = now.getUTCMinutes();
    if (ptDay === 5 && ptHour === 17 && ptMinute < 5) {
      sendWeeklyLetterAuditEmail();
    }
  }, 5 * 60 * 1000);  // check every 5 minutes
  console.log('[letter-audit] Weekly audit scheduler armed (Fridays 5pm PT)');
}

// ─── MODULE EXPORTS ──────────────────────────────────────────────────────────

module.exports = router;
module.exports.init = init;
module.exports.generateAndQueuePhysicianLetter = generateAndQueuePhysicianLetter;
module.exports.notifyPhysicianLetterSkipped = notifyPhysicianLetterSkipped;
