// features/physician-letters.js
// ═════════════════════════════════════════════════════════════════════════════
// PHYSICIAN LETTERS FEATURE — Self-contained module (v2 — two-stage drafting)
// ═════════════════════════════════════════════════════════════════════════════
//
// WORKFLOW (post-eval form fires Converted + toggle ON):
//   1. Post-eval handler calls `notifyPhysicianLetterPending()`.
//   2. Claude generates a PRELIMINARY draft from the eval transcript.
//      - Held silently in audit sheet with status `pending_finalized_note`.
//      - PT is NOT notified yet. Acts as a safety net if finalized note never comes.
//   3. GHL task created for admin (assigned to info@movementclinicpt.com):
//      "Submit finalized eval note for [Patient]" — links to /eval-letter/intake?token=...
//   4. Admin verifies the eval note is signed in PTEverywhere, opens the intake form
//      (pre-filled with patient + PT), copies the signed note as-is, submits.
//   5. Intake form regenerates the FINAL draft using the finalized note as primary source.
//      - Top-level Slack post in #physician-letters @-mentions the PT for review.
//      - Audit row updated to `pending_pt_review`.
//   6. PT reviews, edits any AI drift, attests, approves.
//      - ✅ reaction on PT review message + threaded reply for admin routing.
//   7. Admin enters MD info, generates PDF.
//      - ✅ reaction on routing message + threaded "PDF Ready" reply.
//   8. Admin faxes externally, marks faxed.
//      - ✅ reaction on PDF Ready message + audit row updated.
//
// SKIP PATH (toggle OFF — self-referred patients):
//   - Single non-actionable Slack post: "No physician letter needed — J.M."
//   - Audit row with status 'letter_skipped'.
//   - No Claude call, no admin task, no PT notification.
//
// CANCELLATION PATH (patient lost before fax):
//   - GHL workflow on Closed/Lost stage fires webhook to /eval-letter/cancel
//   - In-flight letter for that contact_id auto-cancelled
//   - Audit row → `cancelled_patient_lost`
//   - Slack notice posted to #physician-letters
//   - GHL admin task auto-completed (if still open)
//   - If letter was already faxed, no automated retraction — logged for human review.
//
// AUDIT TIMING METRICS (surfaced in Friday weekly email):
//   - T1: conversion → finalized note submitted (PT documentation timeliness)
//   - T2: intake submission → PT approval (PT review responsiveness)
//   - T3: PT approval → fax sent (admin fax turnaround)
//
// PUBLIC EXPORTS:
//   module.exports                                  — Express router (mount at /eval-letter)
//   module.exports.init                             — call once on startup (arms weekly cron)
//   module.exports.notifyPhysicianLetterPending     — called by post-eval handler when toggle ON (NEW v2 entry point)
//   module.exports.notifyPhysicianLetterSkipped     — called by post-eval handler when toggle OFF
//   module.exports.generateAndQueuePhysicianLetter  — DEPRECATED v1 entry point — still exported for safety, now aliases notifyPhysicianLetterPending
//
// All env vars are read at the top of this file. All clinical content is
// generated by Claude Sonnet 4.6.
// ═════════════════════════════════════════════════════════════════════════════

const express = require('express');
const axios = require('axios');
const fs = require('fs');
const path = require('path');
const crypto = require('crypto');
const { google } = require('googleapis');
const { Readable } = require('stream');

const router = express.Router();

// ─── CONFIG ──────────────────────────────────────────────────────────────────
// All env vars and constants live here. This is the only place this file
// reads from process.env.

const PHYSICIAN_LETTERS_CHANNEL = process.env.PHYSICIAN_LETTERS_CHANNEL || 'C0B076M7B0E';
const PHYSICIAN_LETTERS_DRIVE_FOLDER = process.env.PHYSICIAN_LETTERS_DRIVE_FOLDER || '1VgLlcCU60c1pvyeQ7-928JgHxnEgSVJr';
const PHYSICIAN_LETTERS_SHEET_ID = process.env.PHYSICIAN_LETTERS_SHEET_ID || '1iM-3NbXz0noloqIY-81EVde9fA_HGM3SGIvmlrxk4lk';
const PHYSICIAN_LETTERS_SHEET_TAB = process.env.PHYSICIAN_LETTERS_SHEET_TAB || 'Sheet1';

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;
const SLACK_BOT_TOKEN = process.env.SLACK_BOT_TOKEN;
const GHL_API_KEY = process.env.GHL_API_KEY;

// GHL user ID for info@movementclinicpt.com (the admin assignee).
// Same value as TASK_ASSIGNEE_ID in main index.js — kept here so this module is self-contained.
const GHL_ADMIN_ASSIGNEE_ID = process.env.GHL_ADMIN_ASSIGNEE_ID || '3EuCG6xznkq3A2CeDhDQ';

// Duplicate prevention window: how recent does a prior in-flight letter for the same
// patient have to be before the intake form warns admin? Default 14 days.
const DUPLICATE_CHECK_WINDOW_DAYS = parseInt(process.env.LETTER_DUPLICATE_WINDOW_DAYS || '14', 10);

const BASE_URL = process.env.RAILWAY_PUBLIC_DOMAIN
  ? `https://${process.env.RAILWAY_PUBLIC_DOMAIN}`
  : 'https://movement-clinic-webhook-production.up.railway.app';

const PT_SLACK_IDS = {
  'John Gan':         'U07TJC6GZFG',
  'TJ Aquino':        'U0A9DL4RTKN',
  'Chris Bostwick':   'U091NMDKTFV',
  'Jordan McCormack': process.env.PT_SLACK_JORDAN || ''
};

const PT_LICENSES = {
  'Jordan McCormack': process.env.PT_LICENSE_JORDAN || 'PT-PENDING',
  'Chris Bostwick':   process.env.PT_LICENSE_CHRIS  || 'PT-PENDING',
  'TJ Aquino':        process.env.PT_LICENSE_TJ     || 'PT-PENDING',
  'John Gan':         process.env.PT_LICENSE_JOHN   || 'PT-PENDING'
};

const PT_CREDENTIALS = {
  'Jordan McCormack': process.env.PT_CREDS_JORDAN || 'PT, DPT',
  'Chris Bostwick':   process.env.PT_CREDS_CHRIS  || 'PT, DPT',
  'TJ Aquino':        process.env.PT_CREDS_TJ     || 'PT, DPT',
  'John Gan':         process.env.PT_CREDS_JOHN   || 'PT, DPT'
};

const ADMIN_TEAM = ['Katy', 'Shane', 'Other'];

const CLINIC = {
  name:    process.env.CLINIC_NAME    || 'Movement Clinic Physical Therapy, Inc.',
  addr1:   process.env.CLINIC_ADDR_1  || '[Clinic Street Address]',
  addr2:   process.env.CLINIC_ADDR_2  || 'Pasadena, CA [ZIP]',
  phone:   process.env.CLINIC_PHONE   || '(626) 669-3778',
  fax:     process.env.CLINIC_FAX     || '[Clinic Fax Number]',
  npi:     process.env.CLINIC_NPI     || '[Clinic Group NPI]',
  website: process.env.CLINIC_WEBSITE || 'movementclinicpt.com'
};

// Persistent storage path — Railway volume in prod, /tmp in dev
const LETTER_DRAFTS_DIR = fs.existsSync('/data')
  ? path.join('/data', 'eval-letters')
  : path.join('/tmp', 'eval-letters');
if (!fs.existsSync(LETTER_DRAFTS_DIR)) {
  fs.mkdirSync(LETTER_DRAFTS_DIR, { recursive: true });
}

// ─── STORAGE HELPERS ─────────────────────────────────────────────────────────

function generateLetterToken() {
  return crypto.randomBytes(16).toString('hex');
}

function saveLetterDraft(token, data) {
  const filePath = path.join(LETTER_DRAFTS_DIR, `${token}.json`);
  fs.writeFileSync(filePath, JSON.stringify(data, null, 2));
}

function loadLetterDraft(token) {
  const filePath = path.join(LETTER_DRAFTS_DIR, `${token}.json`);
  if (!fs.existsSync(filePath)) return null;
  return JSON.parse(fs.readFileSync(filePath, 'utf8'));
}

function listLetterDrafts() {
  if (!fs.existsSync(LETTER_DRAFTS_DIR)) return [];
  return fs.readdirSync(LETTER_DRAFTS_DIR)
    .filter(f => f.endsWith('.json'))
    .map(f => {
      try { return loadLetterDraft(f.replace('.json', '')); }
      catch { return null; }
    })
    .filter(Boolean);
}

function patientInitials(draft) {
  const f = (draft.patient_first_name || '?')[0];
  const l = (draft.patient_last_name || '?')[0];
  return `${f}.${l}.`;
}

// Find an in-flight (non-terminal) letter for a given patient name + contact_id,
// created within the duplicate-check window. Used by the intake form to warn
// admin about possible duplicate submissions.
//
// Terminal statuses (excluded): faxed, cancelled_patient_lost, letter_skipped
// In-flight statuses (included): pending_finalized_note, pending_pt_review,
//                                pending_admin_routing, pdf_ready
function findInFlightLetterForPatient(contactId, firstName, lastName) {
  const drafts = listLetterDrafts();
  const cutoff = Date.now() - DUPLICATE_CHECK_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const TERMINAL = new Set(['faxed', 'cancelled_patient_lost', 'letter_skipped']);

  return drafts.find(d => {
    if (TERMINAL.has(d.status)) return false;
    if (new Date(d.created_at).getTime() < cutoff) return false;
    // Match on contact_id if available, otherwise fall back to name match
    if (contactId && d.ghl_contact_id === contactId) return true;
    if (!contactId && firstName && lastName) {
      return (d.patient_first_name || '').toLowerCase() === firstName.toLowerCase()
          && (d.patient_last_name || '').toLowerCase() === lastName.toLowerCase();
    }
    return false;
  });
}

// ─── CLAUDE LETTER GENERATION ────────────────────────────────────────────────

const LETTER_GENERATION_PROMPT = `You are a clinical writer for Movement Clinic Physical Therapy, an outpatient clinic in Pasadena, CA. You generate professional Initial Evaluation Summary letters that physical therapists send to a patient's referring or primary care physician.

Your output is a structured JSON object that will be reviewed by the evaluating PT before being sent. Be clinically precise, factually grounded in the source material, and avoid embellishment.

CRITICAL RULES:
1. Only include findings that are explicitly stated or unambiguously implied in the source material.
2. If something is not in the source, do NOT make it up. Use "Not assessed during evaluation" or omit the field.
3. Use professional clinical terminology that an MD will recognize (e.g., "external rotator weakness 4-/5", "limited active shoulder flexion ~150°").
4. Distinguish between subjective complaints (what the patient said) and objective findings (what the PT measured).
5. Mark the "confidence" field honestly — "high" if the source was thorough, "medium" if some sections are sparse, "low" if you had to infer significantly.

Return ONLY valid JSON in this exact schema:

{
  "patient_summary": {
    "chief_complaint": "Brief one-sentence summary of primary concern",
    "onset": "Duration and mechanism (e.g., '3.5 months ago, insidious onset, no known trauma')",
    "aggravating_factors": "What makes it worse",
    "relieving_factors": "What makes it better",
    "prior_treatment": "Any prior care for this issue (or 'None reported')"
  },
  "subjective": "2-4 sentence narrative of the patient's reported symptoms, functional limitations, and goals. Written in clinical letter prose.",
  "objective_findings": [
    "Bullet point of an objective finding (e.g., 'Active shoulder flexion limited to 150° vs. 175° on uninvolved side')",
    "Another bullet point",
    "etc."
  ],
  "red_flags_screened": "Brief statement of red flags screened and ruled out (e.g., 'No progressive weakness, no bowel/bladder changes, no unexplained weight loss, no night pain unrelieved by position change.')",
  "assessment": "2-4 sentence clinical assessment / working diagnosis. Use ICF/movement-based language where appropriate.",
  "short_term_goals": [
    "Goal achievable in 4 weeks (functional, measurable)",
    "Another short-term goal",
    "etc. — typically 2-4 goals"
  ],
  "long_term_goals": [
    "Goal achievable in 12 weeks (functional, measurable)",
    "Another long-term goal",
    "etc. — typically 2-4 goals"
  ],
  "plan_of_care": {
    "frequency": "Recommended frequency (e.g., '1-2x/week')",
    "duration": "Recommended duration (e.g., '8-12 weeks')",
    "interventions": [
      "Manual therapy",
      "Therapeutic exercise",
      "Neuromuscular re-education",
      "Patient education and self-management",
      "etc. — only list what's clinically appropriate"
    ]
  },
  "physician_communication_request": "1-2 sentence statement of what we'd like from the physician (typically 'We will continue to update you on the patient's progress. Please contact our office with any questions or if you would like additional information.').",
  "confidence": "high | medium | low",
  "confidence_notes": "If medium or low, briefly explain what was unclear in the source material."
}`;

// Generate a draft using either the eval transcript (preliminary) or the finalized
// PTE note (final). The prompt is identical — only the source material differs.
async function generateLetterDraftWithClaude(sourceMaterial, sourceType, patientFirstName, patientLastName, evaluatingPT) {
  const sourceLabel = sourceType === 'finalized_note' ? 'FINALIZED EVALUATION NOTE' : 'EVAL TRANSCRIPT';
  const userMessage = `PATIENT NAME: ${patientFirstName} ${patientLastName}
EVALUATING PHYSICAL THERAPIST: ${evaluatingPT}

${sourceLabel}:
${sourceMaterial}`;

  const response = await axios.post(
    'https://api.anthropic.com/v1/messages',
    {
      model: 'claude-sonnet-4-6',
      max_tokens: 3000,
      system: [{ type: 'text', text: LETTER_GENERATION_PROMPT }],
      messages: [{ role: 'user', content: userMessage }]
    },
    {
      headers: {
        'x-api-key': ANTHROPIC_API_KEY,
        'anthropic-version': '2023-06-01',
        'Content-Type': 'application/json'
      },
      timeout: 90000
    }
  );

  const text = response.data.content[0].text;
  return JSON.parse(text.replace(/```json|```/g, '').trim());
}

// ─── PDF RENDERING ───────────────────────────────────────────────────────────

function buildLetterHTML(draft) {
  const today = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
  const ptName = draft.evaluating_pt || '';
  const ptCreds = PT_CREDENTIALS[ptName] || 'PT, DPT';
  const ptLicense = PT_LICENSES[ptName] || 'PT-PENDING';

  const c = draft.clinical_content || {};
  const ps = c.patient_summary || {};
  const poc = c.plan_of_care || {};
  const md = draft.physician_routing || {};

  const recipientBlock = md.physician_name
    ? `${md.physician_name}${md.physician_practice ? '<br>' + md.physician_practice : ''}${md.physician_fax ? '<br>Fax: ' + md.physician_fax : ''}`
    : '[Physician Name Pending]';

  const salutationName = md.physician_name
    ? 'Dr. ' + (md.physician_name.split(' ').slice(-1)[0] || 'Physician')
    : 'Physician';

  return `<!DOCTYPE html>
<html>
<head>
<meta charset="utf-8">
<style>
  @page { size: letter; margin: 0.5in 0.6in 0.5in 0.6in; }
  * { box-sizing: border-box; }
  body { font-family: 'Helvetica', 'Arial', sans-serif; font-size: 11pt; line-height: 1.45; color: #000000; margin: 0; padding: 0; }
  .letterhead { border-bottom: 3pt solid #FFD70A; padding-bottom: 14pt; margin-bottom: 20pt; display: table; width: 100%; }
  .letterhead-left { display: table-cell; vertical-align: top; width: 60%; }
  .letterhead-right { display: table-cell; vertical-align: top; width: 40%; text-align: right; font-size: 9.5pt; color: #232323; }
  .clinic-name { font-size: 18pt; font-weight: 700; color: #232323; margin: 0 0 2pt 0; letter-spacing: 0.3pt; }
  .clinic-tagline { font-size: 9pt; color: #4b5563; margin: 0; text-transform: uppercase; letter-spacing: 1pt; }
  .meta-line { margin: 1pt 0; }
  .date-line { margin: 0 0 14pt 0; font-size: 11pt; }
  .recipient { margin: 0 0 14pt 0; line-height: 1.4; }
  .re-line { margin: 0 0 16pt 0; font-weight: 700; font-size: 11pt; }
  .salutation { margin: 0 0 12pt 0; }
  .section-heading { font-weight: 700; margin: 14pt 0 4pt 0; color: #232323; font-size: 11pt; border-bottom: 0.5pt solid #cccccc; padding-bottom: 2pt; }
  .section-body { margin: 0 0 6pt 0; }
  ul.findings { margin: 4pt 0 6pt 0; padding-left: 20pt; }
  ul.findings li { margin-bottom: 3pt; }
  .poc-table { margin: 6pt 0 8pt 0; width: 100%; border-collapse: collapse; }
  .poc-table td { padding: 3pt 0; vertical-align: top; }
  .poc-table td.poc-label { width: 110pt; font-weight: 600; }
  .signature-block { margin-top: 28pt; page-break-inside: avoid; }
  .signature-line { border-top: 0.5pt solid #232323; width: 280pt; margin-top: 36pt; padding-top: 4pt; font-size: 10pt; }
  .signature-name { font-weight: 700; font-size: 11pt; }
  .e-attestation { margin-top: 6pt; font-size: 8.5pt; color: #4b5563; font-style: italic; }
  .footer { margin-top: 30pt; padding-top: 8pt; border-top: 0.5pt solid #cccccc; font-size: 8pt; color: #4b5563; text-align: center; }
</style>
</head>
<body>

<div class="letterhead">
  <div class="letterhead-left">
    <p class="clinic-name">${CLINIC.name}</p>
    <p class="clinic-tagline">Outpatient Physical Therapy &middot; Pasadena, CA</p>
  </div>
  <div class="letterhead-right">
    <div class="meta-line">${CLINIC.addr1}</div>
    <div class="meta-line">${CLINIC.addr2}</div>
    <div class="meta-line">P: ${CLINIC.phone} &nbsp;&middot;&nbsp; F: ${CLINIC.fax}</div>
    <div class="meta-line">NPI: ${CLINIC.npi}</div>
    <div class="meta-line">${CLINIC.website}</div>
  </div>
</div>

<div class="date-line">${today}</div>
<div class="recipient">${recipientBlock}</div>
<div class="re-line">RE: ${draft.patient_first_name || ''} ${draft.patient_last_name || ''} &nbsp;&middot;&nbsp; Initial Evaluation Summary</div>
<div class="salutation">Dear ${salutationName},</div>

<div class="section-body">
This letter is to inform you that your patient, ${draft.patient_first_name || ''} ${draft.patient_last_name || ''}, has been evaluated at our clinic and has begun a course of physical therapy care under our team. The findings, assessment, and recommended plan of care are summarized below for your records.
</div>

<div class="section-heading">Patient Summary</div>
<table class="poc-table">
  <tr><td class="poc-label">Chief Complaint:</td><td>${ps.chief_complaint || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Onset:</td><td>${ps.onset || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Aggravating Factors:</td><td>${ps.aggravating_factors || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Relieving Factors:</td><td>${ps.relieving_factors || 'Not specified'}</td></tr>
  <tr><td class="poc-label">Prior Treatment:</td><td>${ps.prior_treatment || 'None reported'}</td></tr>
</table>

<div class="section-heading">Subjective</div>
<div class="section-body">${c.subjective || ''}</div>

<div class="section-heading">Objective Findings</div>
<ul class="findings">
${(c.objective_findings || []).map(f => `  <li>${f}</li>`).join('\n')}
</ul>

<div class="section-heading">Red Flag Screening</div>
<div class="section-body">${c.red_flags_screened || 'Standard red flag screening completed.'}</div>

<div class="section-heading">Clinical Assessment</div>
<div class="section-body">${c.assessment || ''}</div>

<div class="section-heading">Short-Term Goals (4 weeks)</div>
<ul class="findings">
${(c.short_term_goals || []).map(g => `  <li>${g}</li>`).join('\n')}
</ul>

<div class="section-heading">Long-Term Goals (12 weeks)</div>
<ul class="findings">
${(c.long_term_goals || []).map(g => `  <li>${g}</li>`).join('\n')}
</ul>

<div class="section-heading">Recommended Plan of Care</div>
<table class="poc-table">
  <tr><td class="poc-label">Frequency:</td><td>${poc.frequency || ''}</td></tr>
  <tr><td class="poc-label">Duration:</td><td>${poc.duration || ''}</td></tr>
  <tr><td class="poc-label">Interventions:</td><td>${(poc.interventions || []).join('; ')}</td></tr>
</table>

<div class="section-body" style="margin-top:14pt;">${c.physician_communication_request || 'We will continue to update you on the patient\'s progress. Please contact our office with any questions or if you would like additional information.'}</div>

<div class="signature-block">
  <div>Sincerely,</div>
  <div class="signature-line">
    <div class="signature-name">${ptName}, ${ptCreds}</div>
    <div>CA PT License #: ${ptLicense}</div>
  </div>
  <div class="e-attestation">
    Electronically reviewed and approved by ${ptName}, ${ptCreds} &middot; License ${ptLicense} &middot; on ${draft.pt_approved_at_human || today}
  </div>
</div>

<div class="footer">
  This communication contains confidential health information protected under HIPAA. If you are not the intended recipient, please notify our office immediately and destroy this document.
</div>

</body>
</html>`;
}

async function renderLetterPDF(draft) {
  const puppeteer = require('puppeteer-core');
  const chromium = require('@sparticuz/chromium');

  const html = buildLetterHTML(draft);

  const browser = await puppeteer.launch({
    args: chromium.args,
    defaultViewport: chromium.defaultViewport,
    executablePath: await chromium.executablePath(),
    headless: true
  });

  try {
    const page = await browser.newPage();
    await page.setContent(html, { waitUntil: 'networkidle0' });
    return await page.pdf({
      format: 'Letter',
      printBackground: true,
      margin: { top: '0.5in', bottom: '0.5in', left: '0.6in', right: '0.6in' }
    });
  } finally {
    await browser.close();
  }
}

// ─── GOOGLE WORKSPACE: DRIVE, SHEETS, GMAIL ──────────────────────────────────

function getServiceAccountAuth(scopes) {
  const SERVICE_ACCOUNT_JSON = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '{}');
  return new google.auth.GoogleAuth({ credentials: SERVICE_ACCOUNT_JSON, scopes });
}

async function uploadLetterPDFToDrive(pdfBuffer, filename) {
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/drive']);
  const drive = google.drive({ version: 'v3', auth });

  const stream = new Readable();
  stream.push(pdfBuffer);
  stream.push(null);

  const file = await drive.files.create({
    requestBody: {
      name: filename,
      parents: [PHYSICIAN_LETTERS_DRIVE_FOLDER],
      mimeType: 'application/pdf'
    },
    media: { mimeType: 'application/pdf', body: stream },
    fields: 'id, webViewLink',
    supportsAllDrives: true
  });

  return { id: file.data.id, webViewLink: file.data.webViewLink };
}

// ─── AUDIT SHEET ─────────────────────────────────────────────────────────────
// Sheet schema (v2 — 18 columns):
//   A: Timestamp                    J: Admin Routed By
//   B: Letter ID                    K: Admin Routed At
//   C: Evaluating PT                L: Faxed By
//   D: Patient Initials             M: Faxed At
//   E: Status                       N: Drive Link
//   F: PT Approved At               O: Notes
//   G: MD Name                      P: T1 (conversion → finalized note submitted, hours)
//   H: MD Practice                  Q: T2 (intake submission → PT approval, hours)
//   I: MD Fax                       R: T3 (PT approval → fax sent, hours)

async function appendLetterAuditRow(rowValues) {
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/spreadsheets']);
  const sheets = google.sheets({ version: 'v4', auth });

  await sheets.spreadsheets.values.append({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!A:R`,
    valueInputOption: 'USER_ENTERED',
    insertDataOption: 'INSERT_ROWS',
    requestBody: { values: [rowValues] }
  });
}

async function updateLetterAuditRow(letterId, columnUpdates) {
  // columnUpdates: { K: 'value', L: 'value' } — column-letter -> value
  const auth = getServiceAccountAuth(['https://www.googleapis.com/auth/spreadsheets']);
  const sheets = google.sheets({ version: 'v4', auth });

  // Find the row with this letter ID (column B)
  const lookup = await sheets.spreadsheets.values.get({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!B:B`
  });
  const rows = lookup.data.values || [];
  let rowIndex = -1;
  for (let i = 0; i < rows.length; i++) {
    if (rows[i][0] === letterId) { rowIndex = i + 1; break; }
  }
  if (rowIndex === -1) {
    console.warn(`[letter-audit] Letter ID ${letterId} not found in sheet — skipping update`);
    return;
  }

  const data = Object.entries(columnUpdates).map(([col, val]) => ({
    range: `${PHYSICIAN_LETTERS_SHEET_TAB}!${col}${rowIndex}`,
    values: [[val]]
  }));

  await sheets.spreadsheets.values.batchUpdate({
    spreadsheetId: PHYSICIAN_LETTERS_SHEET_ID,
    requestBody: { valueInputOption: 'USER_ENTERED', data }
  });
}

// Helper: hours between two ISO timestamps, rounded to 1 decimal.
// Returns null if either input is missing.
function hoursBetween(startISO, endISO) {
  if (!startISO || !endISO) return null;
  const start = new Date(startISO).getTime();
  const end = new Date(endISO).getTime();
  if (isNaN(start) || isNaN(end)) return null;
  return Math.round(((end - start) / (1000 * 60 * 60)) * 10) / 10;
}

async function sendWeeklyLetterAuditEmail() {
  try {
    const drafts = listLetterDrafts();
    const oneWeekAgo = Date.now() - 7 * 24 * 60 * 60 * 1000;
    const recent = drafts.filter(d => new Date(d.created_at).getTime() >= oneWeekAgo);

    if (recent.length === 0) {
      console.log('[letter-audit] No letters in the past week — skipping weekly email');
      return;
    }

    const byStatus = {};
    recent.forEach(d => { byStatus[d.status] = (byStatus[d.status] || 0) + 1; });

    const statusRows = Object.entries(byStatus).map(([status, count]) =>
      `<tr><td style="padding:6px 12px; border:1px solid #e5e7eb;">${status}</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${count}</td></tr>`
    ).join('');

    // Compute SLA medians for completed letters this week
    const faxed = recent.filter(d => d.status === 'faxed');
    const t1Values = faxed.map(d => hoursBetween(d.created_at, d.intake_submitted_at)).filter(v => v !== null);
    const t2Values = faxed.map(d => hoursBetween(d.intake_submitted_at, d.pt_approved_at)).filter(v => v !== null);
    const t3Values = faxed.map(d => hoursBetween(d.pt_approved_at, d.faxed_at)).filter(v => v !== null);
    const median = arr => arr.length ? arr.slice().sort((a, b) => a - b)[Math.floor(arr.length / 2)] : null;
    const worst = arr => arr.length ? Math.max(...arr) : null;
    const fmt = v => v === null ? '—' : `${v}h`;

    const slaTable = faxed.length === 0 ? '<p style="font-size:13px; color:#4b5563;">No fully-completed letters this week — SLA metrics will populate once letters are faxed.</p>' : `
<table style="border-collapse:collapse; font-size:13px; width:100%;">
  <thead><tr style="background:#F7F8FA;">
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Stage</th>
    <th style="padding:6px 12px; text-align:right; border:1px solid #e5e7eb;">Median</th>
    <th style="padding:6px 12px; text-align:right; border:1px solid #e5e7eb;">Worst</th>
  </tr></thead>
  <tbody>
    <tr><td style="padding:6px 12px; border:1px solid #e5e7eb;">Conversion → finalized note submitted</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(median(t1Values))}</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(worst(t1Values))}</td></tr>
    <tr><td style="padding:6px 12px; border:1px solid #e5e7eb;">Intake submission → PT approval</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(median(t2Values))}</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(worst(t2Values))}</td></tr>
    <tr><td style="padding:6px 12px; border:1px solid #e5e7eb;">PT approval → fax sent</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(median(t3Values))}</td><td style="padding:6px 12px; border:1px solid #e5e7eb; text-align:right;">${fmt(worst(t3Values))}</td></tr>
  </tbody>
</table>`;

    const detailRows = recent.map(d => `<tr>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${patientInitials(d)}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.evaluating_pt}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.status}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.physician_routing?.physician_name || '—'}</td>
      <td style="padding:6px 12px; border:1px solid #e5e7eb;">${d.faxed_at ? new Date(d.faxed_at).toLocaleDateString() : '—'}</td>
    </tr>`).join('');

    const html = `<!DOCTYPE html>
<html><body style="font-family:'Helvetica',Arial,sans-serif; max-width:680px; margin:0 auto; padding:20px; color:#232323;">
<div style="background:#232323; color:#fff; padding:18px; border-radius:10px;">
  <h2 style="margin:0;">Physician Letter Audit — Weekly Summary</h2>
  <p style="margin:6px 0 0 0; opacity:0.85; font-size:13px;">Week ending ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}</p>
</div>
<h3 style="margin-top:24px;">Status Breakdown</h3>
<table style="border-collapse:collapse; font-size:14px;">
  <thead><tr style="background:#F7F8FA;"><th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Status</th><th style="padding:6px 12px; text-align:right; border:1px solid #e5e7eb;">Count</th></tr></thead>
  <tbody>${statusRows}</tbody>
</table>
<h3 style="margin-top:24px;">SLA Timing (faxed letters this week)</h3>
${slaTable}
<h3 style="margin-top:24px;">Letter Detail (${recent.length} total)</h3>
<table style="border-collapse:collapse; font-size:13px; width:100%;">
  <thead><tr style="background:#F7F8FA;">
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Patient</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">PT</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Status</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">MD</th>
    <th style="padding:6px 12px; text-align:left; border:1px solid #e5e7eb;">Faxed</th>
  </tr></thead>
  <tbody>${detailRows}</tbody>
</table>
<p style="margin-top:24px; font-size:12px; color:#4b5563;">Full audit log: <a href="https://docs.google.com/spreadsheets/d/${PHYSICIAN_LETTERS_SHEET_ID}/edit">Physician Letter Audit Log</a></p>
</body></html>`;

    const SERVICE_ACCOUNT_JSON = JSON.parse(process.env.GOOGLE_SERVICE_ACCOUNT_JSON || '{}');
    const auth = new google.auth.JWT(
      SERVICE_ACCOUNT_JSON.client_email,
      null,
      SERVICE_ACCOUNT_JSON.private_key,
      ['https://www.googleapis.com/auth/gmail.send'],
      'jordan@movementclinicpt.com'
    );
    const gmail = google.gmail({ version: 'v1', auth });

    const subject = `Physician Letter Audit — Week of ${new Date().toLocaleDateString('en-US', { month: 'short', day: 'numeric' })}`;
    const messageParts = [
      'From: jordan@movementclinicpt.com',
      'To: jordan@movementclinicpt.com',
      `Subject: ${subject}`,
      'MIME-Version: 1.0',
      'Content-Type: text/html; charset=utf-8',
      '',
      html
    ];
    const rawMessage = Buffer.from(messageParts.join('\r\n')).toString('base64')
      .replace(/\+/g, '-').replace(/\//g, '_').replace(/=+$/, '');
    await gmail.users.messages.send({ userId: 'me', requestBody: { raw: rawMessage } });
    console.log('[letter-audit] Weekly email sent to Jordan');
  } catch (err) {
    console.error('[letter-audit] Weekly email failed:', err.message);
  }
}

// ─── GHL TASK MANAGEMENT ─────────────────────────────────────────────────────

// Create a task in GHL assigned to info@movementclinicpt.com (admin team).
// Used to notify admin that a new finalized eval note needs to be submitted
// via the intake form. Returns the GHL task ID for later reference (completion).
async function createAdminIntakeTask(contactId, patientFirstName, patientLastName, intakeUrl) {
  if (!contactId || !GHL_API_KEY) {
    console.warn('[letter-ghl] Cannot create admin task — missing contactId or GHL_API_KEY');
    return null;
  }

  // Due date: 7 days out. Provides a reasonable window for PT to finalize the note.
  const dueDate = new Date(Date.now() + 7 * 24 * 60 * 60 * 1000);

  try {
    const response = await axios.post(
      `https://services.leadconnectorhq.com/contacts/${contactId}/tasks`,
      {
        title: `Submit finalized eval note for ${patientFirstName} ${patientLastName}`,
        body: `The post-eval form has been submitted with outcome = Converted. Once ${patientFirstName} ${patientLastName}'s evaluation note is signed and finalized in PTEverywhere, copy the full note and submit it via this intake form to generate the physician letter for review:\n\n${intakeUrl}\n\nDo not submit if the note is still in draft.`,
        dueDate: dueDate.toISOString(),
        completed: false,
        assignedTo: GHL_ADMIN_ASSIGNEE_ID
      },
      { headers: { 'Authorization': `Bearer ${GHL_API_KEY}`, 'Version': '2021-07-28', 'Content-Type': 'application/json' } }
    );
    const taskId = response.data?.task?.id || response.data?.id || null;
    console.log(`[letter-ghl] Admin intake task created — id ${taskId}`);
    return taskId;
  } catch (err) {
    console.error('[letter-ghl] Failed to create admin intake task:', err.response?.data || err.message);
    return null;
  }
}

// Mark an admin intake task as completed in GHL. Called after admin successfully
// submits the finalized note via the intake form, OR on cancellation when the
// in-flight letter is cancelled.
async function completeAdminIntakeTask(contactId, taskId) {
  if (!contactId || !taskId || !GHL_API_KEY) return;
  try {
    await axios.put(
      `https://services.leadconnectorhq.com/contacts/${contactId}/tasks/${taskId}`,
      { completed: true },
      { headers: { 'Authorization': `Bearer ${GHL_API_KEY}`, 'Version': '2021-07-28', 'Content-Type': 'application/json' } }
    );
    console.log(`[letter-ghl] Admin intake task ${taskId} marked complete`);
  } catch (err) {
    console.warn('[letter-ghl] Failed to complete admin intake task:', err.response?.data || err.message);
    // Non-blocking — admin can manually complete in GHL if needed
  }
}

// ─── SLACK NOTIFICATIONS ─────────────────────────────────────────────────────
// All messages are HIPAA-safe — patient initials only, no clinical content,
// no fax numbers. PHI lives in Drive (auth-gated) and the audit sheet.

async function postSlack(channel, text, blocks, thread_ts) {
  const payload = { channel, text, blocks };
  if (thread_ts) payload.thread_ts = thread_ts;
  const response = await axios.post(
    'https://slack.com/api/chat.postMessage',
    payload,
    { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } }
  );
  if (!response.data.ok) {
    console.warn(`[letter-notify] Slack post failed: ${response.data.error}`);
    return null;
  }
  return response.data.ts;
}

async function addReaction(channel, message_ts, emoji = 'white_check_mark') {
  if (!channel || !message_ts || !SLACK_BOT_TOKEN) return;
  try {
    const response = await axios.post(
      'https://slack.com/api/reactions.add',
      { channel, timestamp: message_ts, name: emoji },
      { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } }
    );
    if (!response.data.ok && response.data.error !== 'already_reacted') {
      console.warn(`[letter-notify] Reaction add failed: ${response.data.error}`);
    }
  } catch (err) {
    console.warn(`[letter-notify] Reaction add error: ${err.message}`);
  }
}

// Posts the top-level "ready for review" message to #physician-letters channel.
// @-mentions the evaluating PT. Returns the message ts so the caller can save it.
async function notifyPTForReview(token, draft) {
  const ptName = draft.evaluating_pt;
  const ptSlackId = PT_SLACK_IDS[ptName];
  const reviewUrl = `${BASE_URL}/eval-letter/${token}`;
  const initials = patientInitials(draft);
  const ptMention = ptSlackId ? `<@${ptSlackId}>` : (ptName || 'PT');

  if (!ptSlackId) {
    console.warn(`[letter-notify] No Slack ID for PT "${ptName}" — channel post will use plaintext name instead of @-mention`);
  }

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, `Initial Evaluation Summary ready for review — ${initials}`, [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:clipboard: *Initial Evaluation Summary Ready for Review — ${initials}*\n\n${ptMention} please review the AI-drafted summary that will be sent to this patient's physician. The draft was generated from your finalized PTEverywhere note.` }
    },
    {
      type: 'actions',
      elements: [{ type: 'button', text: { type: 'plain_text', text: 'Review Summary →' }, url: reviewUrl, style: 'primary' }]
    }
  ]);
}

async function notifyAdminForRouting(token, draft) {
  const adminUrl = `${BASE_URL}/eval-letter/${token}/admin`;
  const initials = patientInitials(draft);
  const threadTs = draft.slack_pt_review_ts || null;

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, 'New Initial Evaluation Summary ready for fax routing', [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:fax: *Ready for Fax Routing — ${initials}*\n\nPT has approved. Admin team — please add the physician name + fax number to generate the PDF for faxing.` }
    },
    {
      type: 'actions',
      elements: [{ type: 'button', text: { type: 'plain_text', text: 'Add MD Info & Generate PDF →' }, url: adminUrl, style: 'primary' }]
    }
  ], threadTs);
}

async function notifyAdminPDFReady(token, draft, driveLink) {
  const initials = patientInitials(draft);
  const adminUrl = `${BASE_URL}/eval-letter/${token}/admin`;
  const threadTs = draft.slack_pt_review_ts || null;

  return await postSlack(PHYSICIAN_LETTERS_CHANNEL, 'PDF ready to fax', [
    {
      type: 'section',
      text: { type: 'mrkdwn', text: `:page_facing_up: *PDF Ready to Fax — ${initials}*\n\nFax it from your fax workflow, then come back here and click *Mark as Faxed*.` }
    },
    {
      type: 'actions',
      elements: [
        { type: 'button', text: { type: 'plain_text', text: 'Open in Drive' }, url: driveLink },
        { type: 'button', text: { type: 'plain_text', text: 'Mark as Faxed' }, url: adminUrl, style: 'primary' }
      ]
    }
  ], threadTs);
}

// Posted when patient is lost (Closed/Lost) before letter is faxed.
async function notifyLetterCancelled(draft, reason) {
  const initials = patientInitials(draft);
  const text = `:no_entry: *Letter Cancelled — ${initials}*\n\n${reason}\n\nNo PDF was generated, no fax was sent. Audit row updated.`;
  await postSlack(PHYSICIAN_LETTERS_CHANNEL, `Letter cancelled — ${initials}`, [
    { type: 'section', text: { type: 'mrkdwn', text } }
  ]);
}

async function notifyJordanOfError(errorMsg, patientName) {
  const jordanId = process.env.PT_SLACK_JORDAN;
  if (!jordanId || !SLACK_BOT_TOKEN) return;
  try {
    await axios.post('https://slack.com/api/chat.postMessage', {
      channel: jordanId,
      text: `:warning: Physician letter generation failed for ${patientName}: ${errorMsg}`
    }, { headers: { Authorization: `Bearer ${SLACK_BOT_TOKEN}` } });
  } catch (err) {
    console.error('[letter-notify] Failed to notify Jordan:', err.message);
  }
}

// ─── ORCHESTRATOR (PUBLIC ENTRY POINTS) ──────────────────────────────────────
// These are what the post-eval handler calls. Everything else above is internal.

// v2 ENTRY POINT — Called when outcome=Converted AND PT chose YES on the letter toggle.
//
// What happens:
//   1. Generate a PRELIMINARY draft from the eval transcript (saved to draft, not shown to PT).
//      This is a safety net — if the finalized note never comes in, we still have content.
//   2. Save draft with status `pending_finalized_note`.
//   3. Create a GHL task for admin (info@) with a link to the intake form.
//   4. Write the audit row.
//   5. NO PT notification yet. PT gets notified only after admin submits the finalized note.
async function notifyPhysicianLetterPending(opts) {
  const {
    transcript,
    patient_first_name,
    patient_last_name,
    patient_phone,
    patient_email,
    evaluating_pt,
    contact_id,
    ghl_opportunity_id
  } = opts;

  try {
    console.log(`[letter] Starting v2 workflow for ${patient_first_name} ${patient_last_name} — generating preliminary draft`);

    // Generate preliminary draft from transcript (held silently, never shown to PT)
    const preliminaryContent = await generateLetterDraftWithClaude(
      transcript,
      'transcript',
      patient_first_name,
      patient_last_name,
      evaluating_pt
    );

    const token = generateLetterToken();
    const intakeUrl = `${BASE_URL}/eval-letter/intake?token=${token}`;

    const draft = {
      token,
      letter_id: token,
      created_at: new Date().toISOString(),
      patient_first_name,
      patient_last_name,
      patient_phone,
      patient_email,
      evaluating_pt,
      ghl_contact_id: contact_id,
      ghl_opportunity_id,
      status: 'pending_finalized_note',
      // Preliminary draft (transcript-based) — held as safety net
      preliminary_content: preliminaryContent,
      preliminary_generated_at: new Date().toISOString(),
      // Final clinical content — populated after admin submits finalized note
      clinical_content: null,
      // Source of truth for the final draft
      finalized_note_text: null,
      intake_submitted_at: null,
      intake_submitted_by: null,
      // Physician routing + downstream
      physician_routing: null,
      pt_approved_at: null,
      pt_approved_at_human: null,
      pdf_drive_id: null,
      pdf_drive_link: null,
      faxed_at: null,
      faxed_by: null,
      admin_routed_by: null,
      admin_routed_at: null,
      // GHL task ID so we can complete it on intake submission or cancellation
      ghl_admin_task_id: null,
      // Slack message timestamps
      slack_pt_review_ts: null,
      slack_admin_routing_ts: null,
      slack_pdf_ready_ts: null
    };

    saveLetterDraft(token, draft);

    // Create admin task in GHL (assigned to info@movementclinicpt.com)
    const taskId = await createAdminIntakeTask(contact_id, patient_first_name, patient_last_name, intakeUrl);
    if (taskId) {
      draft.ghl_admin_task_id = taskId;
      saveLetterDraft(token, draft);
    }

    // Initial audit row
    await appendLetterAuditRow([
      new Date().toISOString(),               // A: Timestamp
      token,                                   // B: Letter ID
      evaluating_pt,                           // C: PT
      patientInitials(draft),                  // D: Patient Initials
      'pending_finalized_note',                // E: Status
      '',                                      // F: PT Approved At
      '',                                      // G: MD Name
      '',                                      // H: MD Practice
      '',                                      // I: MD Fax
      '',                                      // J: Admin Routed By
      '',                                      // K: Admin Routed At
      '',                                      // L: Faxed By
      '',                                      // M: Faxed At
      '',                                      // N: Drive Link
      `Preliminary draft confidence: ${preliminaryContent.confidence || 'unknown'}`,  // O: Notes
      '',                                      // P: T1
      '',                                      // Q: T2
      ''                                       // R: T3
    ]);

    console.log(`[letter] Preliminary draft created — token ${token}, awaiting admin intake`);
  } catch (err) {
    console.error('[letter] Preliminary draft generation failed:', err.message);
    await notifyJordanOfError(err.message, `${patient_first_name} ${patient_last_name}`);
  }
}

// DEPRECATED v1 alias — for backward compatibility with main index.js.
// New code should call notifyPhysicianLetterPending instead.
async function generateAndQueuePhysicianLetter(opts) {
  return notifyPhysicianLetterPending(opts);
}

// Called when outcome=Converted AND PT chose NOT to generate a physician letter.
// Posts a "no letter needed" notification to the channel and logs an audit row
// with status 'letter_skipped'. No Claude call, no admin task.
async function notifyPhysicianLetterSkipped(opts) {
  const {
    patient_first_name,
    patient_last_name,
    evaluating_pt,
    contact_id,
    ghl_opportunity_id
  } = opts;

  try {
    console.log(`[letter] Letter skipped for ${patient_first_name} ${patient_last_name} (PT: ${evaluating_pt})`);

    const initials = `${(patient_first_name || '?')[0]}.${(patient_last_name || '?')[0]}.`;

    await postSlack(PHYSICIAN_LETTERS_CHANNEL, `No physician letter needed — ${initials}`, [
      {
        type: 'section',
        text: {
          type: 'mrkdwn',
          text: `:no_entry_sign: *No Physician Letter — ${initials}*\n\n${initials} has converted to Package Purchased. The evaluating PT (*${evaluating_pt}*) chose not to generate a physician letter for this patient.\n\n_Typically this means the patient is self-referred, declined physician communication, or the physician was informed through another channel. No action needed from admin._`
        }
      }
    ]);

    const skipToken = generateLetterToken();
    await appendLetterAuditRow([
      new Date().toISOString(),         // A
      skipToken,                         // B
      evaluating_pt,                     // C
      initials,                          // D
      'letter_skipped',                  // E
      '', '', '', '', '', '', '', '', '', // F-N
      'PT chose not to generate physician letter at submission time', // O
      '', '', ''                         // P-R
    ]);

    console.log(`[letter] Skip event logged — token ${skipToken}`);
  } catch (err) {
    console.error('[letter] Skip notification failed:', err.message);
  }
}

// ─── HTML VIEW: ADMIN INTAKE FORM (NEW v2) ───────────────────────────────────
// Admin lands here from the GHL task link. Form is pre-filled with patient name
// and evaluating PT (from the draft). Admin verifies the PTE note is signed,
// copies it as-is into the textarea, picks who's submitting, and submits.

function renderAdminIntakePage(draft, duplicateWarning) {
  const initials = patientInitials(draft);

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Submit Finalized Eval Note — ${initials}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Montserrat', sans-serif; background: #F7F8FA; color: #232323; margin: 0; padding-top: env(safe-area-inset-top); }
  .header { background: #232323; color: #fff; padding: 18px 20px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
  .header .sub { margin-top: 4px; font-size: 13px; opacity: 0.85; }
  .container { max-width: 760px; margin: 0 auto; padding: 16px; }
  .card { background: #fff; border-radius: 10px; padding: 18px; margin-bottom: 14px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .card h3 { margin: 0 0 12px 0; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; color: #232323; }
  label { display: block; font-size: 12px; font-weight: 600; color: #4b5563; margin: 10px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
  input[type="text"] { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 15px; border: 1px solid #d8dde5; border-radius: 8px; padding: 12px; background: #f3f4f6; color: #4b5563; }
  textarea { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 14px; border: 1px solid #d8dde5; border-radius: 8px; padding: 12px; min-height: 360px; resize: vertical; }
  .radio-group { display: flex; gap: 10px; margin-top: 4px; }
  .radio-pill { flex: 1; }
  .radio-pill input[type="radio"] { display: none; }
  .radio-pill label { display: flex; align-items: center; justify-content: center; padding: 14px 16px; border: 1.5px solid #d8dde5; border-radius: 10px; font-size: 15px; font-weight: 600; cursor: pointer; transition: all 0.15s; user-select: none; background: #fff; color: #232323; text-transform: none; letter-spacing: 0; margin: 0; }
  .radio-pill input[type="radio"]:checked + label { border-color: #0065a3; background: #e6f0f7; color: #0065a3; }
  .btn-primary { background: #FFD70A; color: #232323; border: none; border-radius: 10px; padding: 16px 20px; width: 100%; font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 16px; cursor: pointer; margin-top: 12px; }
  .btn-primary:disabled { background: #e5e7eb; color: #9ca3af; cursor: not-allowed; }
  .status-msg { padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 14px; display: none; }
  .status-msg.error { background: #fde8e8; color: #A02020; }
  .status-msg.success { background: #e7f5ed; color: #1F7A4D; }
  .warning-banner { background: #fff8d6; border: 1.5px solid #FFD70A; border-radius: 8px; padding: 14px; margin-bottom: 14px; font-size: 14px; }
  .warning-banner strong { display: block; margin-bottom: 4px; color: #B85C00; }
  .duplicate-banner { background: #fde8e8; border: 1.5px solid #B91C1C; border-radius: 8px; padding: 14px; margin-bottom: 14px; font-size: 14px; }
  .duplicate-banner strong { display: block; margin-bottom: 4px; color: #B91C1C; }
  .instructions { background: #e6f0f7; border-left: 4px solid #0065a3; padding: 12px 14px; border-radius: 6px; margin-bottom: 14px; font-size: 13px; line-height: 1.5; }
  .instructions strong { display: block; margin-bottom: 6px; }
</style>
</head>
<body>

<div class="header">
  <h1>Submit Finalized Eval Note</h1>
  <div class="sub">Patient: ${initials} &middot; PT: ${draft.evaluating_pt}</div>
</div>

<div class="container">

  ${duplicateWarning ? `
  <div class="duplicate-banner">
    <strong>⚠️ Possible Duplicate</strong>
    A letter is already in progress for this patient (status: ${duplicateWarning.status}, created ${new Date(duplicateWarning.created_at).toLocaleDateString()}). Submitting again will create a second letter. Confirm with the PT before continuing.
  </div>` : ''}

  <div class="instructions">
    <strong>Before you submit:</strong>
    1. Verify the eval note is <strong>signed/finalized</strong> in PTEverywhere. Do not submit a draft note.<br>
    2. Copy the <strong>full signed note as-is</strong>. Do not edit, summarize, or remove anything.<br>
    3. Paste it below and submit. The PT will then receive a Slack notification to review the AI-drafted letter.
  </div>

  <div class="card">
    <h3>Patient Info (auto-filled)</h3>
    <label>Patient Name</label>
    <input type="text" value="${draft.patient_first_name || ''} ${draft.patient_last_name || ''}" disabled>
    <label>Evaluating PT</label>
    <input type="text" value="${draft.evaluating_pt || ''}" disabled>
  </div>

  <div class="card">
    <h3>Finalized Eval Note (from PTEverywhere)</h3>
    <label>Paste the full signed eval note as-is *</label>
    <textarea id="finalized_note" placeholder="Paste the complete signed evaluation note from PTEverywhere here..."></textarea>
    <label style="margin-top: 14px;">Submitted By *</label>
    <div class="radio-group">
      ${ADMIN_TEAM.map((name, idx) => `
      <div class="radio-pill">
        <input type="radio" name="submitted_by" id="submitted_by_${idx}" value="${name}" onclick="toggleSubmittedOther()">
        <label for="submitted_by_${idx}">${name}</label>
      </div>
      `).join('')}
    </div>
    <input type="text" id="submitted_by_other" placeholder="Type name" style="display:none; margin-top:8px; background:#fff; color:#232323;">
    <button type="button" class="btn-primary" id="submitBtn" onclick="submitIntake()">Submit Note &amp; Generate Letter Draft</button>
    <div class="status-msg" id="statusMsg"></div>
  </div>

</div>

<script>
function toggleSubmittedOther() {
  const radio = document.querySelector('input[name="submitted_by"]:checked');
  const otherInput = document.getElementById('submitted_by_other');
  if (radio && radio.value === 'Other') {
    otherInput.style.display = 'block';
    otherInput.focus();
  } else {
    otherInput.style.display = 'none';
    otherInput.value = '';
  }
}

async function submitIntake() {
  const btn = document.getElementById('submitBtn');
  const status = document.getElementById('statusMsg');
  const note = document.getElementById('finalized_note').value.trim();
  const radio = document.querySelector('input[name="submitted_by"]:checked');
  let submittedBy = radio ? radio.value : '';
  if (submittedBy === 'Other') {
    submittedBy = document.getElementById('submitted_by_other').value.trim();
  }

  if (!note) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Paste the finalized eval note before submitting.';
    return;
  }
  if (note.length < 100) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'The eval note seems too short. Make sure you copied the full signed note from PTEverywhere.';
    return;
  }
  if (!submittedBy) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Please select who is submitting (or type a name if you selected Other).';
    return;
  }

  btn.disabled = true;
  btn.textContent = 'Generating draft...';
  status.className = 'status-msg';
  status.style.display = 'block';
  status.style.background = '#F7F8FA';
  status.style.color = '#4b5563';
  status.textContent = 'Generating letter draft from the finalized note... This takes 20-40 seconds.';

  try {
    const res = await fetch('/eval-letter/intake/${draft.token}/submit', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ finalized_note: note, submitted_by: submittedBy })
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.textContent = '✓ Letter draft generated. The PT has been notified in Slack to review it.';
      btn.textContent = '✓ Submitted';
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.textContent = 'Error: ' + err.message;
    btn.disabled = false;
    btn.textContent = 'Submit Note &amp; Generate Letter Draft';
  }
}
</script>

</body>
</html>`;
}

// ─── HTML VIEW: PT REVIEW PAGE ───────────────────────────────────────────────
// (Unchanged from v1 — already renders editable textareas and approve button.)

function renderPTReviewPage(draft) {
  const c = draft.clinical_content || {};
  const ps = c.patient_summary || {};
  const poc = c.plan_of_care || {};
  const initials = patientInitials(draft);
  const isApproved = draft.status !== 'pending_pt_review';
  const confColor = c.confidence === 'high' ? '#1F7A4D' : c.confidence === 'medium' ? '#B85C00' : '#A02020';

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
<title>Initial Evaluation Summary Review — ${initials}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Montserrat', sans-serif; background: #F7F8FA; color: #232323; margin: 0; padding: 0; padding-top: env(safe-area-inset-top); }
  .header { background: #232323; color: #fff; padding: 18px 20px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
  .header .sub { margin-top: 4px; font-size: 13px; opacity: 0.85; }
  .container { max-width: 760px; margin: 0 auto; padding: 16px; }
  .conf-banner { background: #fff; border-left: 5px solid ${confColor}; border-radius: 8px; padding: 14px 16px; margin-bottom: 16px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .conf-label { font-weight: 700; color: ${confColor}; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; }
  .conf-notes { font-size: 13px; margin-top: 6px; color: #555; }
  .card { background: #fff; border-radius: 10px; padding: 16px; margin-bottom: 14px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .card h3 { margin: 0 0 10px 0; font-size: 14px; font-weight: 700; color: #232323; text-transform: uppercase; letter-spacing: 0.5px; border-bottom: 1px solid #eee; padding-bottom: 6px; }
  label.field-label { display: block; font-size: 12px; font-weight: 600; color: #4b5563; margin: 8px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
  textarea, input[type="text"] { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 14px; border: 1px solid #d8dde5; border-radius: 8px; padding: 10px 12px; background: #fff; color: #232323; }
  textarea { min-height: 60px; resize: vertical; }
  textarea.tall { min-height: 120px; }
  .bullet-list { display: flex; flex-direction: column; gap: 6px; }
  .bullet-row { display: flex; gap: 6px; align-items: flex-start; }
  .bullet-row textarea { flex: 1; min-height: 38px; }
  .bullet-remove { background: #f3f4f6; color: #4b5563; border: none; border-radius: 6px; padding: 0 10px; cursor: pointer; font-weight: 700; font-size: 16px; }
  .add-bullet { background: #f3f4f6; color: #4b5563; border: none; border-radius: 6px; padding: 8px 12px; font-family: 'Montserrat', sans-serif; font-weight: 600; font-size: 13px; margin-top: 6px; cursor: pointer; }
  .attestation { background: #fffbe5; border: 1px solid #FFD70A; border-radius: 10px; padding: 14px 16px; margin: 16px 0; }
  .attestation label { display: flex; gap: 12px; align-items: flex-start; cursor: pointer; user-select: none; }
  .attestation input[type="checkbox"] { width: 22px; height: 22px; margin-top: 2px; flex-shrink: 0; }
  .attestation-text { font-size: 13px; line-height: 1.5; }
  .approve-btn { background: #FFD70A; color: #232323; border: none; border-radius: 10px; padding: 16px 20px; width: 100%; font-family: 'Montserrat', sans-serif; font-weight: 700; font-size: 16px; cursor: pointer; margin-top: 8px; }
  .approve-btn:disabled { background: #e5e7eb; color: #9ca3af; cursor: not-allowed; }
  .approved-banner { background: #1F7A4D; color: #fff; padding: 16px; border-radius: 10px; text-align: center; font-weight: 600; }
  .status-msg { padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 14px; display: none; }
  .status-msg.error { background: #fde8e8; color: #A02020; }
  .status-msg.success { background: #e7f5ed; color: #1F7A4D; }
  .row { display: grid; grid-template-columns: 1fr 1fr; gap: 10px; }
  @media (max-width: 600px) { .row { grid-template-columns: 1fr; } }
</style>
</head>
<body>

<div class="header">
  <h1>Initial Evaluation Summary Review</h1>
  <div class="sub">Patient: ${initials} &middot; Evaluating PT: ${draft.evaluating_pt}</div>
</div>

<div class="container">

  ${isApproved ? `<div class="approved-banner">✓ This summary has been approved and is now in the admin queue for routing.</div>` : ''}

  <div class="conf-banner">
    <div class="conf-label">Claude Confidence: ${c.confidence || 'unknown'}</div>
    ${c.confidence_notes ? `<div class="conf-notes">${c.confidence_notes}</div>` : ''}
  </div>

  <form id="reviewForm" ${isApproved ? 'style="opacity:0.6; pointer-events:none;"' : ''}>

    <div class="card">
      <h3>Patient Summary</h3>
      <label class="field-label">Chief Complaint</label>
      <textarea name="chief_complaint">${ps.chief_complaint || ''}</textarea>
      <label class="field-label">Onset</label>
      <textarea name="onset">${ps.onset || ''}</textarea>
      <label class="field-label">Aggravating Factors</label>
      <textarea name="aggravating_factors">${ps.aggravating_factors || ''}</textarea>
      <label class="field-label">Relieving Factors</label>
      <textarea name="relieving_factors">${ps.relieving_factors || ''}</textarea>
      <label class="field-label">Prior Treatment</label>
      <textarea name="prior_treatment">${ps.prior_treatment || ''}</textarea>
    </div>

    <div class="card">
      <h3>Subjective</h3>
      <textarea name="subjective" class="tall">${c.subjective || ''}</textarea>
    </div>

    <div class="card">
      <h3>Objective Findings</h3>
      <div class="bullet-list" id="objective_findings_list">
        ${(c.objective_findings || []).map(f => `<div class="bullet-row"><textarea data-bullet="objective_findings">${f}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('objective_findings_list', 'objective_findings')">+ Add finding</button>
    </div>

    <div class="card">
      <h3>Red Flag Screening</h3>
      <textarea name="red_flags_screened" class="tall">${c.red_flags_screened || ''}</textarea>
    </div>

    <div class="card">
      <h3>Clinical Assessment</h3>
      <textarea name="assessment" class="tall">${c.assessment || ''}</textarea>
    </div>

    <div class="card">
      <h3>Short-Term Goals (4 weeks)</h3>
      <div class="bullet-list" id="short_term_goals_list">
        ${(c.short_term_goals || []).map(g => `<div class="bullet-row"><textarea data-bullet="short_term_goals">${g}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('short_term_goals_list', 'short_term_goals')">+ Add goal</button>
    </div>

    <div class="card">
      <h3>Long-Term Goals (12 weeks)</h3>
      <div class="bullet-list" id="long_term_goals_list">
        ${(c.long_term_goals || []).map(g => `<div class="bullet-row"><textarea data-bullet="long_term_goals">${g}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('long_term_goals_list', 'long_term_goals')">+ Add goal</button>
    </div>

    <div class="card">
      <h3>Plan of Care</h3>
      <div class="row">
        <div><label class="field-label">Frequency</label><input type="text" name="frequency" value="${poc.frequency || ''}"></div>
        <div><label class="field-label">Duration</label><input type="text" name="duration" value="${poc.duration || ''}"></div>
      </div>
      <label class="field-label" style="margin-top:8px;">Interventions</label>
      <div class="bullet-list" id="interventions_list">
        ${(poc.interventions || []).map(intv => `<div class="bullet-row"><textarea data-bullet="interventions">${intv}</textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button></div>`).join('')}
      </div>
      <button type="button" class="add-bullet" onclick="addBullet('interventions_list', 'interventions')">+ Add intervention</button>
    </div>

    <div class="card">
      <h3>Communication to Physician</h3>
      <textarea name="physician_communication_request" class="tall">${c.physician_communication_request || ''}</textarea>
    </div>

    <div class="attestation">
      <label>
        <input type="checkbox" id="attest_check" required>
        <div class="attestation-text">
          I have reviewed this evaluation summary and confirm that it accurately reflects the patient's clinical presentation, my assessment, and my recommended plan of care. I approve it for transmission to the patient's referring physician under my electronic signature as ${draft.evaluating_pt}, ${PT_CREDENTIALS[draft.evaluating_pt] || 'PT, DPT'} (CA PT License: ${PT_LICENSES[draft.evaluating_pt] || 'PT-PENDING'}).
        </div>
      </label>
    </div>

    <button type="button" class="approve-btn" id="approveBtn" disabled onclick="approveLetter()">Approve & Send to Admin</button>
    <div class="status-msg" id="statusMsg"></div>

  </form>

</div>

<script>
function addBullet(listId, name) {
  const list = document.getElementById(listId);
  const row = document.createElement('div');
  row.className = 'bullet-row';
  row.innerHTML = '<textarea data-bullet="' + name + '"></textarea><button type="button" class="bullet-remove" onclick="removeBullet(this)">×</button>';
  list.appendChild(row);
  row.querySelector('textarea').focus();
}
function removeBullet(btn) { btn.parentElement.remove(); }

document.getElementById('attest_check')?.addEventListener('change', e => {
  document.getElementById('approveBtn').disabled = !e.target.checked;
});

function collectBullets(name) {
  return Array.from(document.querySelectorAll('textarea[data-bullet="' + name + '"]'))
    .map(el => el.value.trim()).filter(Boolean);
}

async function approveLetter() {
  const btn = document.getElementById('approveBtn');
  const status = document.getElementById('statusMsg');
  btn.disabled = true;
  btn.textContent = 'Submitting...';

  const payload = {
    clinical_content: {
      patient_summary: {
        chief_complaint: document.querySelector('[name="chief_complaint"]').value,
        onset: document.querySelector('[name="onset"]').value,
        aggravating_factors: document.querySelector('[name="aggravating_factors"]').value,
        relieving_factors: document.querySelector('[name="relieving_factors"]').value,
        prior_treatment: document.querySelector('[name="prior_treatment"]').value
      },
      subjective: document.querySelector('[name="subjective"]').value,
      objective_findings: collectBullets('objective_findings'),
      red_flags_screened: document.querySelector('[name="red_flags_screened"]').value,
      assessment: document.querySelector('[name="assessment"]').value,
      short_term_goals: collectBullets('short_term_goals'),
      long_term_goals: collectBullets('long_term_goals'),
      plan_of_care: {
        frequency: document.querySelector('[name="frequency"]').value,
        duration: document.querySelector('[name="duration"]').value,
        interventions: collectBullets('interventions')
      },
      physician_communication_request: document.querySelector('[name="physician_communication_request"]').value
    }
  };

  try {
    const res = await fetch('/eval-letter/${draft.token}/approve', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(payload)
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.style.display = 'block';
      status.textContent = '✓ Approved. Admin team has been notified to add physician routing info.';
      btn.textContent = '✓ Approved';
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Error: ' + err.message;
    btn.disabled = false;
    btn.textContent = 'Approve & Send to Admin';
  }
}
</script>

</body>
</html>`;
}

// ─── HTML VIEW: ADMIN ROUTING PAGE ───────────────────────────────────────────
// (Unchanged from v1.)

function renderAdminRoutingPage(draft) {
  const initials = patientInitials(draft);
  const md = draft.physician_routing || {};
  const isFaxed = draft.status === 'faxed';
  const pdfReady = draft.pdf_drive_link && !isFaxed;

  return `<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Admin Routing — ${initials}</title>
<link href="https://fonts.googleapis.com/css2?family=Montserrat:wght@400;500;600;700&display=swap" rel="stylesheet">
<style>
  * { box-sizing: border-box; }
  body { font-family: 'Montserrat', sans-serif; background: #F7F8FA; color: #232323; margin: 0; padding-top: env(safe-area-inset-top); }
  .header { background: #232323; color: #fff; padding: 18px 20px; }
  .header h1 { margin: 0; font-size: 20px; font-weight: 700; }
  .header .sub { margin-top: 4px; font-size: 13px; opacity: 0.85; }
  .container { max-width: 600px; margin: 0 auto; padding: 16px; }
  .card { background: #fff; border-radius: 10px; padding: 18px; margin-bottom: 14px; box-shadow: 0 1px 4px rgba(0,0,0,0.06); }
  .card h3 { margin: 0 0 12px 0; font-size: 14px; text-transform: uppercase; letter-spacing: 0.5px; color: #232323; }
  label { display: block; font-size: 12px; font-weight: 600; color: #4b5563; margin: 10px 0 4px 0; text-transform: uppercase; letter-spacing: 0.4px; }
  input[type="text"] { width: 100%; font-family: 'Montserrat', sans-serif; font-size: 15px; border: 1px solid #d8dde5; border-radius: 8px; padding: 12px; }
  .radio-group { display: flex; gap: 10px; margin-top: 4px; }
  .radio-pill { flex: 1; }
  .radio-pill input[type="radio"] { display: none; }
  .radio-pill label { display: flex; align-items: center; justify-content: center; padding: 14px 16px; border: 1.5px solid #d8dde5; border-radius: 10px; font-size: 15px; font-weight: 600; cursor: pointer; transition: all 0.15s; user-select: none; background: #fff; color: #232323; text-transform: none; letter-spacing: 0; margin: 0; }
  .radio-pill input[type="radio"]:checked + label { border-color: #0065a3; background: #e6f0f7; color: #0065a3; }
  .btn-primary { background: #0065a3; color: #fff; border: none; border-radius: 10px; padding: 14px 20px; width: 100%; font-family: 'Montserrat', sans-serif; font-weight: 600; font-size: 15px; cursor: pointer; margin-top: 8px; }
  .btn-primary:disabled { background: #e5e7eb; color: #9ca3af; cursor: not-allowed; }
  .btn-yellow { background: #FFD70A; color: #232323; }
  .btn-success { background: #1F7A4D; }
  .pdf-link { display: block; padding: 12px; background: #F7F8FA; border-radius: 8px; margin: 10px 0; color: #0065a3; text-decoration: none; text-align: center; font-weight: 600; }
  .status-msg { padding: 12px; border-radius: 8px; margin-top: 10px; font-size: 14px; display: none; }
  .status-msg.error { background: #fde8e8; color: #A02020; }
  .status-msg.success { background: #e7f5ed; color: #1F7A4D; }
  .info-row { display: flex; justify-content: space-between; padding: 6px 0; border-bottom: 1px solid #f0f0f0; font-size: 14px; }
  .info-row:last-child { border-bottom: none; }
  .info-label { color: #4b5563; font-weight: 600; }
  .faxed-banner { background: #1F7A4D; color: #fff; padding: 16px; border-radius: 10px; text-align: center; font-weight: 600; }
</style>
</head>
<body>

<div class="header">
  <h1>Initial Evaluation Summary — Routing</h1>
  <div class="sub">Patient: ${initials} &middot; PT: ${draft.evaluating_pt}</div>
</div>

<div class="container">

  ${isFaxed ? `<div class="faxed-banner">✓ Faxed by ${draft.faxed_by} on ${new Date(draft.faxed_at).toLocaleString('en-US', { dateStyle: 'medium', timeStyle: 'short' })}</div>` : ''}

  <div class="card">
    <h3>Letter Status</h3>
    <div class="info-row"><span class="info-label">Status</span><span>${draft.status}</span></div>
    <div class="info-row"><span class="info-label">PT Approved</span><span>${draft.pt_approved_at_human || '—'}</span></div>
    ${draft.physician_routing ? `
    <div class="info-row"><span class="info-label">MD Name</span><span>${draft.physician_routing.physician_name}</span></div>
    <div class="info-row"><span class="info-label">MD Fax</span><span>${draft.physician_routing.physician_fax}</span></div>
    ` : ''}
  </div>

  ${!isFaxed && !pdfReady && draft.status === 'pending_admin_routing' ? `
  <div class="card">
    <h3>Physician Routing Info</h3>
    <label>Physician Name *</label>
    <input type="text" id="physician_name" value="${md.physician_name || ''}" placeholder="Dr. Jane Smith">
    <label>Physician Practice (optional)</label>
    <input type="text" id="physician_practice" value="${md.physician_practice || ''}" placeholder="Pasadena Family Medicine">
    <label>Fax Number *</label>
    <input type="text" id="physician_fax" value="${md.physician_fax || ''}" placeholder="(626) 555-0123">
    <label>Routed By *</label>
    <div class="radio-group">
      ${ADMIN_TEAM.map((name, idx) => `
      <div class="radio-pill">
        <input type="radio" name="admin_name" id="admin_name_${idx}" value="${name}" onclick="toggleAdminOther()">
        <label for="admin_name_${idx}">${name}</label>
      </div>
      `).join('')}
    </div>
    <input type="text" id="admin_name_other" placeholder="Type name" style="display:none; margin-top:8px;">
    <button type="button" class="btn-primary btn-yellow" onclick="generatePdf()">Generate PDF & Notify Fax Queue</button>
    <div class="status-msg" id="statusMsg"></div>
  </div>` : ''}

  ${pdfReady ? `
  <div class="card">
    <h3>PDF Ready</h3>
    <a href="${draft.pdf_drive_link}" target="_blank" class="pdf-link">📄 Open PDF in Drive</a>
    <p style="font-size:13px; color:#4b5563;">Fax it from your fax workflow, then mark it as faxed below.</p>
    <label>Faxed By *</label>
    <div class="radio-group">
      ${ADMIN_TEAM.map((name, idx) => `
      <div class="radio-pill">
        <input type="radio" name="faxed_by" id="faxed_by_${idx}" value="${name}" onclick="toggleFaxedOther()">
        <label for="faxed_by_${idx}">${name}</label>
      </div>
      `).join('')}
    </div>
    <input type="text" id="faxed_by_other" placeholder="Type name" style="display:none; margin-top:8px;">
    <button type="button" class="btn-primary btn-success" onclick="markFaxed()">Mark as Faxed</button>
    <div class="status-msg" id="statusMsg2"></div>
  </div>` : ''}

  ${draft.status === 'pending_finalized_note' ? `
  <div class="card">
    <h3 style="color:#A02020;">⚠️ Not Ready</h3>
    <p>This letter is awaiting submission of the finalized eval note. Once admin submits it via the intake form (linked from the GHL task), the PT will be notified to review.</p>
  </div>` : ''}

  ${draft.status === 'pending_pt_review' ? `
  <div class="card">
    <h3 style="color:#A02020;">⚠️ Not Ready</h3>
    <p>This letter is still pending PT review. The admin routing step will become available once the PT approves it.</p>
  </div>` : ''}

  ${draft.status === 'cancelled_patient_lost' ? `
  <div class="card">
    <h3 style="color:#A02020;">Cancelled</h3>
    <p>This letter was cancelled because the patient's opportunity moved to Closed/Lost. No PDF was generated and no fax was sent.</p>
  </div>` : ''}

</div>

<script>
function toggleAdminOther() {
  const adminRadio = document.querySelector('input[name="admin_name"]:checked');
  const otherInput = document.getElementById('admin_name_other');
  if (adminRadio && adminRadio.value === 'Other') {
    otherInput.style.display = 'block';
    otherInput.focus();
  } else {
    otherInput.style.display = 'none';
    otherInput.value = '';
  }
}

async function generatePdf() {
  const name = document.getElementById('physician_name').value.trim();
  const fax = document.getElementById('physician_fax').value.trim();
  const practice = document.getElementById('physician_practice').value.trim();
  const adminRadio = document.querySelector('input[name="admin_name"]:checked');
  let adminName = adminRadio ? adminRadio.value : '';
  if (adminName === 'Other') {
    adminName = document.getElementById('admin_name_other').value.trim();
  }
  const status = document.getElementById('statusMsg');

  if (!name || !fax || !adminName) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Physician name, fax number, and selecting who routed are all required (type a name if you selected Other).';
    return;
  }

  status.className = 'status-msg';
  status.style.display = 'block';
  status.style.background = '#F7F8FA';
  status.style.color = '#4b5563';
  status.textContent = 'Generating PDF...';

  try {
    const res = await fetch('/eval-letter/${draft.token}/generate-pdf', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ physician_name: name, physician_fax: fax, physician_practice: practice, admin_name: adminName })
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.textContent = '✓ PDF generated. Reloading...';
      setTimeout(() => location.reload(), 1200);
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.textContent = 'Error: ' + err.message;
  }
}

function toggleFaxedOther() {
  const byRadio = document.querySelector('input[name="faxed_by"]:checked');
  const otherInput = document.getElementById('faxed_by_other');
  if (byRadio && byRadio.value === 'Other') {
    otherInput.style.display = 'block';
    otherInput.focus();
  } else {
    otherInput.style.display = 'none';
    otherInput.value = '';
  }
}

async function markFaxed() {
  const byRadio = document.querySelector('input[name="faxed_by"]:checked');
  let by = byRadio ? byRadio.value : '';
  if (by === 'Other') {
    by = document.getElementById('faxed_by_other').value.trim();
  }
  const status = document.getElementById('statusMsg2');
  if (!by) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Please select who faxed it (type a name if you selected Other).';
    return;
  }
  try {
    const res = await fetch('/eval-letter/${draft.token}/mark-faxed', {
      method: 'POST',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify({ faxed_by: by })
    });
    const data = await res.json();
    if (data.success) {
      status.className = 'status-msg success';
      status.style.display = 'block';
      status.textContent = '✓ Marked as faxed. Reloading...';
      setTimeout(() => location.reload(), 1200);
    } else { throw new Error(data.error || 'Unknown error'); }
  } catch (err) {
    status.className = 'status-msg error';
    status.style.display = 'block';
    status.textContent = 'Error: ' + err.message;
  }
}
</script>

</body>
</html>`;
}

// ─── EXPRESS ROUTES ──────────────────────────────────────────────────────────

// NEW v2 ROUTE: Admin intake form (GET)
// Loaded via the GHL task link. Pre-filled with patient + PT from the draft token.
router.get('/intake', (req, res) => {
  const token = req.query.token;
  if (!token) return res.status(400).send('<h1>Missing token</h1><p>This page must be opened from a valid GHL task link.</p>');

  const draft = loadLetterDraft(token);
  if (!draft) return res.status(404).send('<h1>Letter not found</h1><p>This intake link may have expired.</p>');

  if (draft.status !== 'pending_finalized_note') {
    return res.status(409).send(`<h1>Already submitted</h1><p>This letter is no longer in the intake stage (current status: ${draft.status}). It has either already been submitted or has been cancelled.</p>`);
  }

  // Check for an in-flight letter for the same patient (duplicate guard)
  // — but exclude THIS draft from the check
  let duplicateWarning = null;
  const others = listLetterDrafts().filter(d => d.token !== token);
  const TERMINAL = new Set(['faxed', 'cancelled_patient_lost', 'letter_skipped']);
  const cutoff = Date.now() - DUPLICATE_CHECK_WINDOW_DAYS * 24 * 60 * 60 * 1000;
  const dup = others.find(d => {
    if (TERMINAL.has(d.status)) return false;
    if (new Date(d.created_at).getTime() < cutoff) return false;
    if (draft.ghl_contact_id && d.ghl_contact_id === draft.ghl_contact_id) return true;
    return false;
  });
  if (dup) duplicateWarning = dup;

  res.send(renderAdminIntakePage(draft, duplicateWarning));
});

// NEW v2 ROUTE: Admin submits the finalized eval note
// Regenerates the letter draft using the finalized note as primary source,
// then notifies the PT for review.
router.post('/intake/:token/submit', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });

    if (draft.status !== 'pending_finalized_note') {
      return res.status(409).json({ error: `Letter is not in pending_finalized_note state (current: ${draft.status})` });
    }

    const { finalized_note, submitted_by } = req.body;
    if (!finalized_note || !submitted_by) {
      return res.status(400).json({ error: 'Missing finalized_note or submitted_by' });
    }
    if (finalized_note.length < 100) {
      return res.status(400).json({ error: 'Finalized note seems too short — please paste the full signed note' });
    }

    // Regenerate the letter draft using the finalized note as primary source
    console.log(`[letter-intake] Regenerating draft from finalized note for ${draft.patient_first_name} ${draft.patient_last_name}`);
    const finalContent = await generateLetterDraftWithClaude(
      finalized_note,
      'finalized_note',
      draft.patient_first_name,
      draft.patient_last_name,
      draft.evaluating_pt
    );

    // Update draft state
    draft.clinical_content = finalContent;
    draft.finalized_note_text = finalized_note;
    draft.intake_submitted_at = new Date().toISOString();
    draft.intake_submitted_by = submitted_by;
    draft.status = 'pending_pt_review';
    saveLetterDraft(req.params.token, draft);

    // Notify PT in Slack — top-level message in #physician-letters
    const ptReviewTs = await notifyPTForReview(req.params.token, draft);
    if (ptReviewTs) {
      draft.slack_pt_review_ts = ptReviewTs;
      saveLetterDraft(req.params.token, draft);
    }

    // Mark the GHL task complete
    if (draft.ghl_admin_task_id && draft.ghl_contact_id) {
      await completeAdminIntakeTask(draft.ghl_contact_id, draft.ghl_admin_task_id);
    }

    // Update audit row
    const t1Hours = hoursBetween(draft.created_at, draft.intake_submitted_at);
    await updateLetterAuditRow(req.params.token, {
      'E': 'pending_pt_review',
      'O': `Intake submitted by ${submitted_by} · Final draft confidence: ${finalContent.confidence || 'unknown'}`,
      'P': t1Hours !== null ? t1Hours : ''
    });

    res.json({ success: true });
  } catch (err) {
    console.error('[letter intake submit] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// NEW v2 ROUTE: GHL cancellation webhook
// Receives a webhook from a GHL workflow when an opportunity moves to Closed/Lost.
// Cancels any in-flight letter for that contact (does nothing if already faxed).
//
// Expected payload (from GHL workflow):
//   { contact_id: "...", opportunity_id: "...", reason?: "..." }
router.post('/cancel', async (req, res) => {
  try {
    const { contact_id, opportunity_id, reason } = req.body || {};
    if (!contact_id) return res.status(400).json({ error: 'contact_id required' });

    const drafts = listLetterDrafts();
    const TERMINAL = new Set(['faxed', 'cancelled_patient_lost', 'letter_skipped']);
    const candidates = drafts.filter(d =>
      d.ghl_contact_id === contact_id && !TERMINAL.has(d.status)
    );

    if (candidates.length === 0) {
      console.log(`[letter-cancel] No in-flight letters for contact ${contact_id}`);
      return res.json({ success: true, cancelled: 0, message: 'No in-flight letters for this contact' });
    }

    let cancelledCount = 0;
    for (const draft of candidates) {
      draft.status = 'cancelled_patient_lost';
      draft.cancelled_at = new Date().toISOString();
      draft.cancellation_reason = reason || 'Patient opportunity moved to Closed/Lost';
      saveLetterDraft(draft.token, draft);

      await updateLetterAuditRow(draft.token, {
        'E': 'cancelled_patient_lost',
        'O': `Cancelled — ${draft.cancellation_reason}`
      });

      // Complete the GHL admin task if still open
      if (draft.ghl_admin_task_id && draft.ghl_contact_id) {
        await completeAdminIntakeTask(draft.ghl_contact_id, draft.ghl_admin_task_id);
      }

      // Slack notice
      await notifyLetterCancelled(draft, draft.cancellation_reason);
      cancelledCount++;
    }

    console.log(`[letter-cancel] Cancelled ${cancelledCount} letter(s) for contact ${contact_id}`);
    res.json({ success: true, cancelled: cancelledCount });
  } catch (err) {
    console.error('[letter cancel] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// PT review page
router.get('/:token', (req, res) => {
  const draft = loadLetterDraft(req.params.token);
  if (!draft) return res.status(404).send('<h1>Letter not found</h1><p>This letter draft may have expired or been removed.</p>');

  if (draft.status === 'pending_finalized_note') {
    return res.status(409).send('<h1>Not Ready</h1><p>This letter is awaiting submission of the finalized eval note from admin. You will be notified in Slack when it is ready for your review.</p>');
  }

  res.send(renderPTReviewPage(draft));
});

router.post('/:token/approve', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });

    // Idempotency guard — prevents double-approval if button click duplicates
    if (draft.status !== 'pending_pt_review') {
      return res.status(409).json({ error: `Letter has already been approved (current status: ${draft.status})` });
    }

    const { clinical_content } = req.body;
    if (!clinical_content) return res.status(400).json({ error: 'Missing clinical_content' });

    draft.clinical_content = clinical_content;
    draft.status = 'pending_admin_routing';
    draft.pt_approved_at = new Date().toISOString();
    draft.pt_approved_at_human = new Date().toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' });
    saveLetterDraft(req.params.token, draft);

    const t2Hours = hoursBetween(draft.intake_submitted_at, draft.pt_approved_at);
    await updateLetterAuditRow(req.params.token, {
      'E': 'pending_admin_routing',
      'F': draft.pt_approved_at,
      'Q': t2Hours !== null ? t2Hours : ''
    });

    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_pt_review_ts);

    const adminTs = await notifyAdminForRouting(req.params.token, draft);
    if (adminTs) {
      draft.slack_admin_routing_ts = adminTs;
      saveLetterDraft(req.params.token, draft);
    }

    res.json({ success: true });
  } catch (err) {
    console.error('[letter approve] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

router.get('/:token/admin', (req, res) => {
  const draft = loadLetterDraft(req.params.token);
  if (!draft) return res.status(404).send('<h1>Letter not found</h1>');
  res.send(renderAdminRoutingPage(draft));
});

router.post('/:token/generate-pdf', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });
    if (draft.status !== 'pending_admin_routing') {
      return res.status(409).json({ error: 'Letter is not in pending_admin_routing state (current: ' + draft.status + ')' });
    }

    const { physician_name, physician_fax, physician_practice, admin_name } = req.body;
    if (!physician_name || !physician_fax || !admin_name) {
      return res.status(400).json({ error: 'Missing required fields' });
    }

    draft.physician_routing = {
      physician_name,
      physician_fax,
      physician_practice: physician_practice || ''
    };
    draft.admin_routed_by = admin_name;
    draft.admin_routed_at = new Date().toISOString();
    draft.status = 'pdf_ready';

    const pdfBuffer = await renderLetterPDF(draft);

    const dateStr = new Date().toISOString().split('T')[0];
    const cleanLast = (draft.patient_last_name || 'Patient').replace(/[^a-zA-Z0-9]/g, '');
    const cleanFirst = (draft.patient_first_name || '').replace(/[^a-zA-Z0-9]/g, '');
    const filename = `${cleanLast}_${cleanFirst}_${dateStr}.pdf`;

    const driveResult = await uploadLetterPDFToDrive(pdfBuffer, filename);
    draft.pdf_drive_id = driveResult.id;
    draft.pdf_drive_link = driveResult.webViewLink;
    saveLetterDraft(req.params.token, draft);

    await updateLetterAuditRow(req.params.token, {
      'E': 'pdf_ready',
      'G': physician_name,
      'H': physician_practice || '',
      'I': physician_fax,
      'J': admin_name,
      'K': draft.admin_routed_at,
      'N': driveResult.webViewLink
    });

    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_admin_routing_ts);

    const pdfReadyTs = await notifyAdminPDFReady(req.params.token, draft, driveResult.webViewLink);
    if (pdfReadyTs) {
      draft.slack_pdf_ready_ts = pdfReadyTs;
      saveLetterDraft(req.params.token, draft);
    }

    res.json({ success: true, drive_link: driveResult.webViewLink });
  } catch (err) {
    console.error('[letter generate-pdf] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

router.post('/:token/mark-faxed', async (req, res) => {
  try {
    const draft = loadLetterDraft(req.params.token);
    if (!draft) return res.status(404).json({ error: 'Letter not found' });

    // Idempotency guard
    if (draft.status === 'faxed') {
      return res.status(409).json({ error: 'This letter has already been marked as faxed' });
    }
    if (draft.status !== 'pdf_ready') {
      return res.status(409).json({ error: `Letter is not ready to be marked as faxed (current status: ${draft.status})` });
    }

    const { faxed_by } = req.body;
    if (!faxed_by) return res.status(400).json({ error: 'faxed_by required' });

    draft.faxed_by = faxed_by;
    draft.faxed_at = new Date().toISOString();
    draft.status = 'faxed';
    saveLetterDraft(req.params.token, draft);

    const t3Hours = hoursBetween(draft.pt_approved_at, draft.faxed_at);
    await updateLetterAuditRow(req.params.token, {
      'E': 'faxed',
      'L': faxed_by,
      'M': draft.faxed_at,
      'R': t3Hours !== null ? t3Hours : ''
    });

    await addReaction(PHYSICIAN_LETTERS_CHANNEL, draft.slack_pdf_ready_ts);

    res.json({ success: true });
  } catch (err) {
    console.error('[letter mark-faxed] error:', err.message);
    res.status(500).json({ error: err.message });
  }
});

// ─── INITIALIZATION (CALLED FROM MAIN INDEX.JS) ──────────────────────────────

function init() {
  setInterval(() => {
    const now = new Date();
    const ptOffset = -8;
    const ptHour = (now.getUTCHours() + ptOffset + 24) % 24;
    const ptDay = now.getUTCDay();
    const ptMinute = now.getUTCMinutes();
    if (ptDay === 5 && ptHour === 17 && ptMinute < 5) {
      sendWeeklyLetterAuditEmail();
    }
  }, 5 * 60 * 1000);
  console.log('[letter-audit] Weekly audit scheduler armed (Fridays 5pm PT)');
}

// ─── MODULE EXPORTS ──────────────────────────────────────────────────────────

module.exports = router;
module.exports.init = init;
module.exports.notifyPhysicianLetterPending = notifyPhysicianLetterPending;
module.exports.notifyPhysicianLetterSkipped = notifyPhysicianLetterSkipped;
module.exports.generateAndQueuePhysicianLetter = generateAndQueuePhysicianLetter;  // DEPRECATED — alias for v1 callers
